---
title: "Indicateurs"
author: "FD"
date: "`r format(Sys.Date(), '%d-%B-%Y')`"
output: 
  html_document:
    code_folding: hide
    toc: true
    toc_float: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_knit$set(global.par = TRUE)
```


```{r}
today <- Sys.Date() # today's date
```

```{r}
# Whether to generate a gif
doGif <- TRUE
lang <- "EN" #"FR" 
```


Mise à jour du `r today`.   
Source des données : <https://www.data.gouv.fr/fr/datasets/synthese-des-indicateurs-de-suivi-de-lepidemie-covid-19/>

# Generic functions and parameters

```{r}
# Function to compute a sliding window 
sliding.window <- function(v, winwdt = 7, pos = 4, na.rm = TRUE){
  # v vector to be averaged/summed
  # winwdt width of the window 
  # pos position of the focal day in the window
  # FUN function to apply
  n <- length(v)
  # Initialize output vector
  out <- 0 * v + (-1)
  out[1:(pos-1)] <- NA
  out[(n + 1 - winwdt + pos) : n] <- NA
  
  for(i in pos : (n - winwdt + pos)){
    out[i] <- mean(v[(i - pos + 1):(i + winwdt - pos)], na.rm = na.rm)
  }
  return(out[1:n])
}
```

# Load and clean data

```{r}
URL <- "https://www.data.gouv.fr/fr/datasets/r/f335f9ea-86e3-4ffa-9684-93c009d5e617"
dataFile <- paste0("data/FranceIndic_", today, ".csv") # name file with today's date
download.file(URL, dataFile) # download file from repo
dat.France <- read.csv(dataFile, sep = ",", stringsAsFactors = FALSE)
```

Remove leading NAs
```{r}
ibegin <- which(!is.na(dat.France$hosp | !is.na(dat.France$rea)))[1]
dat.France <- dat.France[-(1:ibegin), ]
```

Compute sliding window average
```{r}
dat.France$incid_hosp_ave7 <- sliding.window(dat.France$incid_hosp)
```

Transform dates as decimals
```{r}
year <- substr(dat.France$date, 1, 4) # Extract year
nbdays <- rep(365, nrow(dat.France)) # Number of days in the year
nbdays[year == "2020"] <- 366 # 2020 is leap year

dat.France$fracYear <- as.numeric(base::as.Date(dat.France$date) - base::as.Date(paste0(year, "-01-01"))) / nbdays # Fraction of the year
```


```{r eval = FALSE}
# Just for console evaluation
head(dat.France)
```

```{r}
# Polar coordinates: r, theta
# x = r * cos(theta)
# y = r * sin(theta)

frac2angle <- function(frac){
  # Transform fraction of year into an angle in radian
  - frac * 2 * pi + pi/2
}
polar2xy <- function(r, frac){
  maxval <- max(abs(r), na.rm = TRUE) # Get max value to center the plot
  theta <- frac2angle(frac) # angle value in radian, rotate clockwise
  
  # Polar to cartesian coordinates
  x <- r * cos(theta)
  y <- r * sin(theta)

  list(x = x, y = y, maxval = maxval)  
}

col2020 <- "#0072B2"
col2021 <- "#D55E00"
cols <- rep(col2020, nrow(dat.France))
cols[year == "2021"] <- col2021
makeTransparent<-function(someColor, alpha = 100){
  # Source : https://stackoverflow.com/questions/8047668/transparent-equivalent-of-given-color
  newColor <- col2rgb(someColor)
  apply(newColor, 2, function(curcoldata){rgb(red = curcoldata[1], 
                                              green = curcoldata[2],
                                              blue = curcoldata[3], 
                                              alpha = alpha, 
                                              maxColorValue = 255)})
}
colsTrp <- makeTransparent(cols, 70)
```

```{r}
addLegendPlot <- function(iend, graduations1, graduations2, r, dfinal, valfinal){
  # graduations1 main graduations for number in concentric circles
  # graduations2 sub graduations
  # r radius of months / time legend
  # dfinal fraction of the last day
  # valfinal value on the last day
  
  gmax <- max(c(graduations1, graduations2))
  lwd.grad <- 1.2
  
  for(i in graduations1){
    cxy <- polar2xy(i, seq(0, 1, length.out = 100))
    lines(cxy$x, cxy$y, type = "l", col = "gray", lwd = lwd.grad)
  }
  for(i in graduations2){
    cxy <- polar2xy(i, seq(0, 1, length.out = 100))
    lines(cxy$x, cxy$y, type = "l", col = "gray", lty = 3, lwd = lwd.grad)
  }
  for(i in graduations1){
  text(x = 0, y = graduations1, labels = graduations1, col = "gray", cex = 0.7, adj = c(0.5, -0.2) )
  text(x = 0, y = -graduations1, labels = graduations1, col = "gray", cex = 0.7, adj = c(0.5, +1.2) )
  }
  
  
  # Add months legend
  if(lang == "FR"){
    months <- c("Jan", "Fev", "Mar", "Avr", "Mai", "Jun", "Jui", "Aou", "Sep", "Oct", "Nov", "Dec")
  }else{
    months <- c("Jan", "Feb", "Mar", "Apr", "May", "Jun", "Jul", "Aug", "Sep", "Oct", "Nov", "Dec")    
  }
  
  thetas <- (1:12)/12 - 0.5/12 # Angles of the months
  for(i in seq_along(months)){
    text(x = r * cos(frac2angle(thetas[i])), y = r * sin(frac2angle(thetas[i])), labels = months[i], srt = 90 - thetas[i]*360, col = gray(0.5))
  }
  
  # Add line to locate the current days
  
  # Line to show the date
  lines(c(0, gmax * cos(dfinal)), c(0, gmax * sin(dfinal)))
  # Text with the date
  text(x = r * cos(dfinal), y = r * sin(dfinal), labels = dat.France[iend, "date"], srt = 90 - dat.France[iend, "fracYear"]*360, adj = c(0.2, 0.5), cex = 0.75, col = "black", )
  
  text(x = 0, y = r, adj = c(0, 0), labels = " 2021", col = col2021)
  text(x = 0, y = r, adj = c(1, 0), labels = "2020 ", col = col2020)
  
  # Add circle to locate the value
    fxy <- polar2xy(valfinal, seq(0, 1, length.out = 100))
    lines(fxy$x, fxy$y, type = "l", col = "black", lty = 1.5, lwd = lwd.grad)
}
```

# Hospitalisations 

```{r}
pxy <- polar2xy(dat.France$hosp, dat.France$fracYear)
```

```{r}
plotHosp <- function(iend = nrow(dat.France)){
  
# Initalize plot
par(pty="s")
par(mar = rep(3.5, 4))
rg <- 1.1 * c(- pxy$maxval, pxy$maxval)
plot(0, 0, type = "n", xlim = rg, ylim = rg, 
     xlab = "", ylab = "", 
     asp = 1, 
     axes = FALSE
     )

par(xpd = TRUE)

graduations1 <- c(10000, 20000, 30000)
graduations2 <- c(graduations1 - 5000, 35000)
r <- 40000 # Radius of the month labels
dfinal <- frac2angle(dat.France[iend, "fracYear"]) # End day of the plot
valfinal <- dat.France[iend, "hosp"]

addLegendPlot(iend, graduations1, graduations2, r, dfinal, valfinal)


if(lang == "FR"){
  title(main = "COVID-19, patients hospitalisés", line = 2.5)
}else{
  title(main = "COVID-19, hospitalized patients", line = 2.5)
}


#text(x = 0, y = -r - 5000, labels = paste0("Source des données : ", URL, "
#Mise à jour : ", today, " | ", "@flodebarre"), adj = c(0.5, 1), cex = 0.75)

par(xpd = FALSE)


points(pxy$x[1:iend], pxy$y[1:iend], col = cols, pch = 16, cex = 0.5)

#legend(x = "topright", col = c(col2020, col2021), pch = 16, legend = c(expression("2020", col = "blue"), "2021"), cex = 0.8, pt.cex = 0.5, bty = "n")

if(lang == "FR"){
  mtext(side = 1, text = paste0("Source des données : ", URL, "
Mise à jour : ", today, " | ", "@flodebarre"), cex = 0.75, line = 2)
}else{
  mtext(side = 1, text = paste0("Data : ", URL, "
Date : ", today, " | ", "@flodebarre"), cex = 0.75, line = 2)
}

}
plotHosp()
```

```{r}
if(doGif){
  for(iend in 1:nrow(dat.France)){
    png(filename = paste0("pics/hosp_", sprintf("%04d", iend), ".png"), width = 700, height = 700, pointsize = 20)
    plotHosp(iend)
    dev.off()
  }
  
  # Convert into gif
  system("convert -quality 100% -delay 0.1 -loop 0 pics/hosp*.png pics/animationHosp.gif")
  
  # Convert into movie
  system("convert -quality 100% -delay 0.12 -loop 0 pics/hosp*.png pics/animationHosp.mp4")
  
  # Remove temporary files
  system("rm pics/hosp*.png")
}

# Just re-do the last one
iend <- nrow(dat.France)
png(filename = paste0("pics/hosp_", sprintf("%04d", iend), ".png"), width = 700, height = 700, pointsize = 20)
plotHosp(iend)
dev.off()
```

# Rea / soins intensifs

```{r}
pxy <- polar2xy(dat.France$rea, dat.France$fracYear)
```

```{r}
plotRea <- function(iend = nrow(dat.France)){
  
# Initalize plot
par(pty="s")
par(mar = rep(3.5, 4))
rg <- 1.1 * c(- pxy$maxval, pxy$maxval)
plot(0, 0, type = "n", xlim = rg, ylim = rg, 
     xlab = "", ylab = "", 
     asp = 1, 
     axes = FALSE
     )

par(xpd = TRUE)

graduations1 <- c(2000, 4000, 6000)
graduations2 <- c(graduations1 - 1000, 7000)
r <- 8000
dfinal <- frac2angle(dat.France[iend, "fracYear"]) # End day of the plot
valfinal <- dat.France[iend, "rea"]


addLegendPlot(iend, graduations1, graduations2, r, dfinal, valfinal)

if(lang == "FR"){
  title(main = "COVID-19, réanimation ou soins intensifs", line = 2.5)
}else{
  title(main = "COVID-19, intensive care", line = 2.5)
}

#text(x = 0, y = -r - 500, labels = paste0("Source des données : ", URL, "
#Mise à jour : ", today, " | ", "@flodebarre"), adj = c(0.5, 1), cex = 0.75)

par(xpd = FALSE)


points(pxy$x[1:iend], pxy$y[1:iend], col = cols, pch = 16, cex = 0.5)

#legend(x = "topright", col = c(col2020, col2021), pch = 16, legend = c(expression("2020", col = "blue"), "2021"), cex = 0.8, pt.cex = 0.5, bty = "n")

if(lang == "FR"){
  mtext(side = 1, text = paste0("Source des données : ", URL, "
Mise à jour : ", today, " | ", "@flodebarre"), cex = 0.75, line = 2)
}else{
  mtext(side = 1, text = paste0("Data : ", URL, "
Date : ", today, " | ", "@flodebarre"), cex = 0.75, line = 2)
}

}
plotRea()
```

```{r}
if(doGif){
  for(iend in 1:nrow(dat.France)){
    png(filename = paste0("pics/rea_", sprintf("%04d", iend), ".png"), width = 700, height = 700, pointsize = 20)
    plotRea(iend)
    dev.off()
  }

  # Convert into gif
  system("convert -quality 100% -delay 0.1 -loop 0 pics/rea*.png pics/animationRea.gif")
  
  # Convert into movie
  system("convert -quality 100% -delay 0.12 -loop 0 pics/rea*.png pics/animationRea.mp4")  
  
  # Remove temporary files
  system("rm pics/rea*.png")
}

# Just re-do the last one
iend <- nrow(dat.France)
png(filename = paste0("pics/rea_", sprintf("%04d", iend), ".png"), width = 700, height = 700, pointsize = 20)
plotRea(iend)
dev.off()
```

# Correlation cas / autre indicateur

```{r}
dat.France$pos_ave7 <- sliding.window(dat.France$pos)
dat.France$dc_ave7 <- sliding.window(c(NA, diff(dat.France$dc_tot)))
dat.France$dchosp_ave7 <- sliding.window(c(NA, diff(dat.France$dchosp)))

dat.France$rea_ave7 <- sliding.window(dat.France$incid_rea)


plot(as.Date(dat.France$date), dat.France$pos_ave7, type = "l")
lines(as.Date(dat.France$date), dat.France$incid_hosp_ave7, col = 2)
lines(as.Date(dat.France$date), dat.France$dc_ave7, col = 3)
lines(as.Date(dat.France$date), dat.France$rea_ave7, col = 4)

n <- nrow(dat.France)

corr_hosp <- function(dt){
  v1 <- dat.France[1:(n-dt), "pos_ave7"]
  v2 <- dat.France[(1+dt):n, "incid_hosp_ave7"]
  cr <- mean(v1 * v2, na.rm = TRUE)
  cr
}

corr_mort <- function(dt){
  v1 <- dat.France[1:(n-dt), "pos_ave7"]
  v2 <- dat.France[(1+dt):n, "dc_ave7"]
  cr <- mean(v1 * v2, na.rm = TRUE)
  cr
  }

corr_mort2 <- function(dt){
  v1 <- dat.France[1:(n-dt), "pos_ave7"]
  v2 <- dat.France[(1+dt):n, "dchosp_ave7"]
  cr <- mean(v1 * v2, na.rm = TRUE)
  cr
  }

corr_rea <- function(dt){
  v1 <- dat.France[1:(n-dt), "pos_ave7"]
  v2 <- dat.France[(1+dt):n, "rea_ave7"]
  cr <- mean(v1 * v2, na.rm = TRUE)
  cr
  }

colCas <- rgb(0, 0, 0.75)
colHosp <- rgb(0.9, 0, 0)
colRea <- rgb(0.6, 0, 0.6)
colDeath <- gray(0.4)

dt <- 1
corr_hosp(2)
times <- 0:40
crh <- unlist(lapply(times, corr_hosp))
crd <- unlist(lapply(times, corr_mort))
crd2 <- unlist(lapply(times, corr_mort2))
rea <- unlist(lapply(times, corr_rea))
plot(times, crh/max(crh), ylab = "relative correlation", col = colHosp, xlab = "décalage avec les cas", frame.plot = FALSE)
points(times, crd/max(crd), pch = 2, col = colDeath)
points(times, crd2/max(crd2), pch = 3, col = colDeath)
points(times, rea/max(rea), pch = 3, col = colRea)

argmaxh <- times[which(crh == max(crh))]
argmaxd <- times[which(crd == max(crd))]
argmaxd2 <- times[which(crd2 == max(crd2))]
argmaxrea <- times[which(rea == max(rea))]
abline(v = argmaxh, col = colHosp)
abline(v = argmaxd, col = colDeath)
abline(v = argmaxd2, col = colDeath, lty = 2)
abline(v = argmaxrea, col = colRea, lty = 1)
rm(dt)
c(argmaxh, argmaxd)

xmin <- which(!is.na(dat.France$pos_ave7))[1]
xmin
dat.France2 <- dat.France[xmin:nrow(dat.France), ]

xx <- seq(as.Date("2020-03-01"), as.Date("2021-08-01"), by = "month")

lwdd <- 1.5
ymax <- max(c(dat.France$incid_hosp_ave7/max(dat.France2$incid_hosp_ave7, na.rm = TRUE), dat.France$dc_ave7/max(dat.France2$dc_ave7, na.rm = TRUE)), na.rm = TRUE)

par(las = 1, mgp = c(3, 0.2, 0), tck = -0.01)
plot(as.Date(dat.France$date), dat.France$pos_ave7 / max(dat.France2$pos_ave7, na.rm = TRUE), log = "", col = colCas, frame.plot = FALSE, lwd = lwdd, axes = FALSE, 
     ylim = c(0.01, ymax), 
     type = "n", 
     xlab = "date", ylab = "nombre relatif"#, xlim = range(as.Date(dat.France2$date))
     )

for(i in seq(0, ymax, by = 0.1)){
  abline(h = i, lwd = 0.5, col = gray(0.9))
}

lines(as.Date(dat.France$date), dat.France$pos_ave7 / max(dat.France2$pos_ave7, na.rm = TRUE), lwd = lwdd, col = colCas)


axis(1, at = xx, labels = format.Date(xx, "%Y-%b"), las = 3, cex.axis = 0.7)
axis(2)
lines(as.Date(dat.France[1:(n - argmaxh), "date"]), dat.France[(1+argmaxh):n, "incid_hosp_ave7"]/max(dat.France2[(1+argmaxh:n), "incid_hosp_ave7"], na.rm = TRUE), col = colHosp, lwd = lwdd)
lines(as.Date(dat.France[1:(n - argmaxrea), "date"]), dat.France[(1+argmaxrea):n, "rea_ave7"]/max(dat.France2[(1 + argmaxrea:n), "rea_ave7"], na.rm = TRUE), col = colRea, lwd = lwdd)

#lines(as.Date(dat.France[1:(n - argmaxd), "date"]), dat.France[(1+argmaxd):n, "dc_ave7"]/max(dat.France2[(1+argmaxd:n), "dc_ave7"], na.rm = TRUE), col = colDeath, lwd = lwdd)

lines(as.Date(dat.France[1:(n - argmaxd), "date"]), dat.France[(1+argmaxd):n, "dchosp_ave7"]/max(dat.France2[(1+argmaxd:n), "dchosp_ave7"], na.rm = TRUE), col = colDeath, lwd = lwdd)

add_legend <- function(...) {
  opar <- par(fig=c(0, 1, 0, 1), oma=c(0, 0, 0, 0), 
    mar=c(0, 0, 0, 0), new=TRUE)
  on.exit(par(opar))
  plot(0, 0, type='n', bty='n', xaxt='n', yaxt='n')
  legend(...)
}

legend(x = as.Date(dat.France[1, "date"]), y = ymax, legend = c("cas", paste0("nv hospi (J-", argmaxh, ")"), paste0("nv rea (J-", argmaxrea, ")"), paste0("morts hospi (J-", argmaxd2, ")")), col = c(colCas, colHosp, colRea, colDeath), lty = 1, cex = 0.7, inset = c(0, -0.1), xpd = TRUE, yjust = 0, bty = "n", lwd = lwdd, ncol = 2)

```

# By age classes

```{r}
# https://www.data.gouv.fr/en/datasets/donnees-hospitalieres-relatives-a-lepidemie-de-covid-19/
# par classe d'age
URL <- "https://www.data.gouv.fr/en/datasets/r/08c18e08-6780-452d-9b8c-ae244ad529b3"
dataFile <- paste0("data/FranceHosp_", today, ".csv") # name file with today's date
download.file(URL, dataFile) # download file from repo
dat.Hosp <- read.csv(dataFile, sep = ";", stringsAsFactors = FALSE)

head(dat.Hosp)


```

# UK, correlation cases / deaths by age class

```{r, eval = FALSE}
# Download files
download.file("https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=E92000001&metric=cumAdmissionsByAge&format=csv", "data/UK_admissions.csv")
download.file("https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=E92000001&metric=cumAdmissionsByAge&format=csv", "data/UK_admissions.csv")
download.file("https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=E92000001&metric=newDeaths28DaysByDeathDateAgeDemographics&format=csv", "data/UK_deaths.csv")

# Vaccination complete
download.file("https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=E92000001&metric=cumVaccinationCompleteCoverageByVaccinationDatePercentage&format=csv", "data/UK_vaccination-full.csv")
# 
# https://api.coronavirus.data.gov.uk/v2/data?areaType=nation&areaCode=E92000001&metric=cumVaccinationFirstDoseUptakeByVaccinationDatePercentage&format=csv
```

```{r}
uk.cases <- read.csv("data/UK_cases.csv", sep = ",", stringsAsFactors = FALSE)
uk.admis <- read.csv("data/UK_admissions.csv", sep = ",", stringsAsFactors = FALSE)
uk.death <- read.csv("data/UK_deaths.csv", sep = ",", stringsAsFactors = FALSE)
uk.vaccfull <- read.csv("data/UK_vaccination-full.csv", sep = ",", stringsAsFactors = FALSE)
```

```{r}
head(uk.vaccfull)
# Not by age :-(
```



```{r}

corr_vv <- function(V1, V2, dt){
  v1 <- v1[1:(n-dt)]
  v2 <- v2[(1+dt):n]
  cr <- mean(v1 * v2, na.rm = TRUE)
  cr
}
```

Combine age classes

```{r}
rm(tmp, tmp1, tmp2)
ageClasses <- list("00_19" = c("00_04", "05_09", "10_14", "15_19"), 
                   "20_29" = c("20_24", "25_29"), 
                   "30_39" = c("30_34", "35_39"), 
                   "40_49" = c("40_44", "45_49"),
                   "50_59" = c("50_54", "55_59"),
                   "60_80" = c("60_64", "65_69", "70_74", "75_79"), 
                   "80+" = c("80_84", "85_89", "90+"))

ageClasses



for (ac in names(ageClasses)){
  fname <- paste0("fig_", ac, ".png")
  png(fname, width = 1000, height = 1000, res = 200)
  
  cc <- uk.cases[which(is.element(uk.cases$age, ageClasses[[ac]])),]
  agg.cases <- aggregate(cc$cases, by = list(date = cc$date), FUN = sum)
  names(agg.cases)[2] <- "cases"
  agg.cases$cases_ave7 <- sliding.window(agg.cases$cases)
  rm(cc)
  
  cd <- uk.death[which(is.element(uk.death$age, ageClasses[[ac]])),]
  agg.deaths <- aggregate(cd$deaths, by = list(date = cd$date), FUN = sum)
  names(agg.deaths)[2] <- "deaths"

  agg.deaths$deaths_ave7 <- sliding.window(agg.deaths$deaths)
  rm(cd)
  
  agg <- merge(agg.cases, agg.deaths, by = "date")
  # Remove NA
  agg <- agg[!is.na(agg$cases_ave7) & !is.na(agg$deaths_ave7), ]
  
  # Compute correlation
  times <- 1:35
  n <- nrow(agg)
  dea <- unlist(lapply(times, function(dt) mean(agg[1:(n-dt), "cases_ave7"] * agg[(1+dt):n, "deaths_ave7"], na.rm = TRUE)))
#  plot(times, dea, main = ac)
  argmaxdea <- times[which(dea == max(dea))]
#  abline(v = argmaxdea)
  
  factor <- -10
  par(mgp = c(3, 0.25, 0), tck = -0.01)
  ymax <- 15000
  ymin <- -10000
  plot(as.Date(agg$date), agg$cases_ave7, type = "l", col = colCas, ylim = c(ymin, ymax), xaxs = "i", xlim = range(as.Date(agg$date)), axes = FALSE, 
       xlab = "Date", ylab = "")
  
  lines(as.Date(agg$date)[1:(n - argmaxdea)], factor * agg$deaths_ave7[(1 + argmaxdea):n], type = "l", col = colDeath)
  
  alf <- 0.6
  polygon(c(as.Date(agg$date), rev(as.Date(agg$date)), as.Date(agg$date)[1]), c(agg$cases_ave7, rep(0, n), agg$cases_ave7[1]), col = adjustcolor(colCas, alpha.f = alf), border = gray(0, 0), lwd = 0.01)
  
  #polygon(c(as.Date(agg$date[1:(n - argmaxdea)]), rev(as.Date(agg$date[1:(n - argmaxdea)])), as.Date(agg$date)[1]), factor* c(rep(0, n - argmaxdea), rev(agg$deaths_ave7[(1 + argmaxdea):n]), 0), col = adjustcolor(colDeath, alpha.f = alf), border = gray(0, 0), lwd = 0.01)
  
    
  #lines(as.Date(agg$date)[1:(n - argmaxdea)], factor * tmp$deaths_ave7[(1 + argmaxdea):n], type = "l", col = colDeath, lwd = 3)
  
  polygon(x = c(as.Date(agg$date)[1:(n - argmaxdea)], rev(as.Date(agg$date)[1:(n - argmaxdea)]), as.Date(agg$date[1])), 
          y = factor * c(agg$deaths_ave7[(1 + argmaxdea):n], rep(0, n - argmaxdea), agg$deaths_ave7[1 + argmaxdea]), col = adjustcolor(colDeath, alpha.f = alf), border = adjustcolor(colDeath, alpha.f = alf))
  
  title(main = paste0("England, ages ", ac))
  
  xx <- seq(as.Date("2020-01-01"), as.Date("2021-08-01"), by = "month")
  axis(1, at = xx, labels = format(xx, "%Y-%b"), las = 3, cex.axis = 0.7)
  
  cexx <- 0.9
  axis(2, at = seq(0, ymax, by = 2500), las = 1, col = colCas, col.axis = colCas, cex.axis = cexx)
  
  zz <- seq(0, ymin/factor, by = 250)
  axis(2, at = zz*factor, labels = zz, las = 1, col = colDeath, col.axis = colDeath, cex.axis = cexx)
  
  mtext(side = 3, line = 0, cex = 0.8, text = paste0("lag = ", argmaxdea, " days"))
  
  par(xpd = TRUE)
  xxx <- "2020-04-01"
  text(as.Date(xxx), ymax, adj = c(0, 1), labels = "Cases", col = colCas)
  text(as.Date(xxx), ymin, adj = c(0, 0), labels = "Deaths", col = colDeath)
  par(xpd = FALSE)
  
  mtext(paste0(format(Sys.time(), "%Y-%m-%d"), "
@flodebarre, adapted from @jburnmurdoch","
Data: https://coronavirus.data.gov.uk/details/download"), col = gray(0.5), side = 1, adj = 1, cex = 0.55, line = 4)
  
  dev.off()
  
  system(paste0("open ", fname))
  
  nchar(fname)
  ff <- substr(fname, 1, nchar(fname) - 4)
  ff
#  system(paste0("convert ", fname, " -resize 1000 -quality 72 -background white -alpha remove -flatten -alpha off ", ff, ".png"))
  
#  system(paste0("open ", ff, ".png"))

  
  }
system("convert -delay 100 fig_*.png fig.gif")
```


```{r}

theage <- "90+"
tmp1 <- uk.cases[uk.cases$age == theage, ]
tmp2 <- uk.death[uk.death$age == theage, ]

# Compute sliding window averages
stopifnot(!any(duplicated(tmp1$date)))
stopifnot(!any(duplicated(tmp2$date)))
# Sort by date
tmp1 <- tmp1[order(tmp1$date), ]
tmp2 <- tmp2[order(tmp2$date), ]

tmp <- merge(tmp1, tmp2, by = "date", all = TRUE)

tmp$cases_ave7 <- sliding.window(tmp$cases)
tmp$deaths_ave7 <- sliding.window(tmp$deaths)


plot(as.Date(tmp$date), tmp$cases, col = gray(0.5), pch = 16, cex = 0.2)
lines(as.Date(tmp$date), tmp$cases_ave7, col = colCas)
lines(as.Date(tmp$date), tmp$deaths_ave7, col = colDeath)

times <- 0:40


unique(uk.cases$age)
unique(uk.admis$age)
unique(uk.death$age)



n <- nrow(tmp)
dea <- unlist(lapply(times, function(dt) mean(tmp[1:(n-dt), "cases_ave7"] * tmp[(1+dt):n, "deaths_ave7"], na.rm = TRUE)))
plot(times, dea)

argmaxdea <- times[which(dea == max(dea))]
abline(v = argmaxdea)

n <- nrow(tmp)

plot(as.Date(tmp$date), tmp$cases_ave7/max(tmp$cases_ave7, na.rm = TRUE), type = "l", col = colCas)
lines(as.Date(tmp$date), tmp$deaths_ave7/max(tmp$deaths_ave7, na.rm = TRUE), type = "l", col = colDeath)

factor <- -4
plot(as.Date(tmp$date), tmp$cases_ave7, type = "l", col = colCas, ylim = c(-5000, 10000))

lines(as.Date(tmp$date)[1:(n - argmaxdea)], factor * tmp$deaths_ave7[(1 + argmaxdea):n], type = "l", col = colDeath)

alf <- 0.6
polygon(c(as.Date(tmp$date), rev(as.Date(tmp$date)), as.Date(tmp$date)[1]), c(rep(0, n), rev(tmp$cases_ave7), 0), col = adjustcolor(colCas, alpha.f = alf), border = gray(0, 0), lwd = 0.01)

polygon(c(as.Date(tmp$date[1:(n - argmaxdea)]), rev(as.Date(tmp$date[1:(n - argmaxdea)])), as.Date(tmp$date)[1]), factor* c(rep(0, n - argmaxdea), rev(tmp$deaths_ave7[(1 + argmaxdea):n]), 0), col = adjustcolor(colDeath, alpha.f = alf), border = gray(0, 0), lwd = 0.01)

```



