---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

Source: <https://www.insee.fr/fr/statistiques/4487988?sommaire=4487854>

# Load data

## With data by death location 

(This is not used in the end, but kept for legacy; you can skip this section. I am keeping it because it was useful to decipher some names in the other file)

```{r, fig.show='hide'}
dat1 <- read.csv("data/INSEE_2022-03-25_deces_sexe_age_lieu_csv/2022-03-24_deces_parlieu_jour_France.csv", sep = ";", fileEncoding = "latin1")

# Clean dates
dts <- as.data.frame(matrix(unlist(strsplit(dat1$Date_evenement, split = c("-"))), byrow = TRUE, ncol = 2))
names(dts) <- c("jour", "mois")

dicoMois <- formatC(x = 1:12, width = 2, flag = 0)
names(dicoMois) <- unique(dts[, 2])
dicoMois

dat1$month <- dicoMois[dts$mois]
dat1$day <- dts$jour


# Compute daily deaths
for(col in names(dat1)[2:16]){
  dat1[, paste0("dailyDeaths_", col)] <- c(dat1[1, col], diff(dat1[, col]))
}

mm <- mM <- c()
for(col in names(dat1)[2:16]){
  mM <- c(mM, max(dat1[, paste0("dailyDeaths_", col)], na.rm = TRUE))
  mm <- c(mm, min(dat1[, paste0("dailyDeaths_", col)], na.rm = TRUE))
}
max(mM)
min(mm)
yM <- max(mM)
ym <- min(mm)

plot(0, type = "n", xlim = as.Date(c("2019-01-01", "2022-03-01")), ylim = c(0, 1.05*yM))
for(yr in c(2019, 2021, 2022)){
  for(loc in c("Hopital_Clinique", "Maison_retraite", "Domicile", "Autre")){
    points(as.Date(paste0(yr, "-", dat1$month, "-", dat1$day)), dat1[, paste0("dailyDeaths_", loc, "_Deces", yr)])
  }
}


  points(as.Date(paste0(yr, "-", dat1$month, "-", dat1$day)), dat1$dailyDeaths_Maison_retraite_Deces2019, ylim = c(0, yM))
  points(as.Date(paste0(yr, "-", dat1$month, "-", dat1$day)), dat1$dailyDeaths_Domicile_Deces2019, ylim = c(0, yM))
  points(as.Date(paste0(yr, "-", dat1$month, "-", dat1$day)), dat1$dailyDeaths_Autre_Deces2019, ylim = c(0, yM))  

head(dat1)
names(dat1)
```

## Geographic data

```{r}
# Code geographique
# Source: https://www.insee.fr/fr/information/6051727
coms <- read.csv("data/commune_2022.csv")
dim(coms)
head(coms)

# Create dictionary
dicComReg <- coms$REG
names(dicComReg) <- coms$COM

# Regions
regs <- read.csv("data/region_2022.csv")
dicReg <- regs$LIBELLE
names(dicReg) <- regs$REG

# Departements
dicComDep <- coms$DEP
names(dicComDep) <- coms$COM

deps <- read.csv("data/departement_2022.csv")
dicDep <- deps$LIBELLE
names(dicDep) <- deps$DEP
```

## Colors

```{r}
# Define colors
library("MetBrewer")
cols <- met.brewer("Kandinsky", 6)[1:5]
names(cols) <- c("HopCli", "HosMar", "Logem", "Autres", "Non renseigne")

# Rename columns
dicoNames <- c("Hopital ou Clinique", "Maison de retraite", "Domicile", "Autre", "Non renseigné")
names(dicoNames) <- names(cols)
```

## Load individual data

```{r}
# Load data
DC2018 <- read.csv("data/INSEE_2022-03-25_detail_mortalite/DC_2018_det.csv", sep = ";")
DC2019 <- read.csv("data/INSEE_2022-03-25_detail_mortalite/DC_2019_det.csv", sep = ";")
DC2020 <- read.csv("data/INSEE_2022-03-25_detail_mortalite/DC_2020_det.csv", sep = ";")
DC2021 <- read.csv("data/INSEE_2022-03-25_detail_mortalite/DC_20212022_det.csv", sep = ";")

dat <- do.call("rbind", list(DC2018, DC2019, DC2020, DC2021))
dim(dat)
# Clean memory
rm(DC2018, DC2019, DC2020, DC2021)

# Add geographic information
dat$codeRegion <- dicComReg[dat$COMDOM]
dat$nomRegion <- dicReg[as.character(dat$codeRegion)]

dat$codeDep <- dicComDep[dat$COMDOM]
dat$nomDep <- dicDep[dat$codeDep]

# Reformat date
dat$dateDC <- as.Date(paste0(dat$ADEC, "-", formatC(dat$MDEC, width = 2, flag = 0), "-", formatC(dat$JDEC, width = 2, flag = 0)))
```

# First plots

```{r}
# Aggregate the data at the level of the whole country
datAgg <- aggregate(dat$LIEUDEC2, by = list(lieu = dat$LIEUDEC2, dateDC = dat$dateDC), FUN = length)
datAggTot <- aggregate(dat$LIEUDEC2, by = list(dateDC = dat$dateDC), FUN = length)

unique(dat$COMDOM)


dat[1,]
# Make sure that all dates are present
nn <- unique(table(datAgg$lieu))
nn

head(datAgg)


# Check legend
plot(datAgg$dateDC, datAgg$x)
 points(as.Date(paste0(2019, "-", dat1$month, "-", dat1$day)), dat1[, paste0("dailyDeaths_", "Hopital_Clinique", "_Deces", 2019)], col = 2)
 points(as.Date(paste0(2019, "-", dat1$month, "-", dat1$day)), dat1[, paste0("dailyDeaths_", "Maison_retraite", "_Deces", 2019)], col = 3)
 points(as.Date(paste0(2019, "-", dat1$month, "-", dat1$day)), dat1[, paste0("dailyDeaths_", "Domicile", "_Deces", 2019)], col = 4)
 points(as.Date(paste0(2019, "-", dat1$month, "-", dat1$day)), dat1[, paste0("dailyDeaths_", "Autre", "_Deces", 2019)], col = 5)

plot(datAggTot$dateDC, datAggTot$x, ylim = c(0, max(datAggTot$x)))

# Initialize plot
plot(datAggTot$dateDC, datAggTot$x, ylim = c(0, max(datAggTot$x)), type = "n")

xx <- unique(datAgg$dateDC)
v <- rep(0, nn)
for(lieu in rev(names(cols))){
  tmp <- datAgg[datAgg$lieu == lieu, ]
  # Make sure that all dates are consecutive
  stopifnot(all(diff(tmp$dateDC)==1))
  
  polygon(c(xx, rev(xx), xx[1]), 
          c(v, rev(v + tmp$x), v[1]), col = cols[lieu], lwd = 0.5)
  
  v <- v + tmp$x
}

```

```{r}
mnth <- seq(as.Date("2018-01-01"), max(dat$dateDC), by = "month")
```

```{r}
reg <- "Île-de-France"
fname <- paste0("pics/INSEE-DC_", reg, ".png")
png(fname, width = 16, height = 9, units = "in", res = 300)
# Subset of the data with this region
subdat <- dat[dat$nomRegion == reg, ]

# Aggregate
datAgg <- aggregate(subdat$LIEUDEC2, by = list(lieu = subdat$LIEUDEC2, dateDC = subdat$dateDC), FUN = length)
datAggTot <- aggregate(subdat$LIEUDEC2, by = list(dateDC = subdat$dateDC), FUN = length)

# Initialize plot
plot(datAggTot$dateDC, datAggTot$x, ylim = c(0, max(datAggTot$x)), type = "n", axes = FALSE, 
     xlab = "", ylab = "")
axis(1, pos = 0, at = mnth, labels = format(mnth, "%b\n%Y"), padj = 0.5)
axis(2, pos = min(mnth), las = 1)
mtext(side = 2, las = 3, text = "Nombres de décès quotidiens")
xx <- unique(datAgg$dateDC)
xxd <- data.frame(dateDC = xx) # as data frame
v <- rep(0, nn)
for(lieu in rev(names(cols))){
  tmp <- datAgg[datAgg$lieu == lieu, ]
  # Make sure that all dates are consecutive
  if(!all(diff(tmp$dateDC)==1)){
    # If not, add the missing days as NAs
    tmp <- merge(tmp, xxd, by = "dateDC", all = TRUE)
    tmp[is.na(tmp$x), "x"] <- 0
  }
  
  polygon(c(xx, rev(xx), xx[1]), 
          c(v, rev(v + tmp$x), v[1]), col = cols[lieu], lwd = 0.5)
  
  v <- v + tmp$x
}
legend(x = min(mnth)+10, y = max(v), col = cols, legend = dicoNames[names(cols)], pch = 15, title = "Lieux de décès", pt.cex = 3, y.intersp = 1.5, x.intersp = 1.5, box.lwd = 0)
title(main = reg)

dev.off()
system(paste0("open ", fname))
```

```{r}
# Load population sizes
# Source: https://www.insee.fr/fr/statistiques/2012713
popDep <- read.csv("data/INSEE_popDep.csv")
head(popDep)
popReg <- read.csv("data/INSEE_popRegion.csv")
head(popReg)
```

# Polar figure

## By region

```{r}
source("polarFunctions.R")
source("usefulFunctions.R")

# Define colors
colYear <- met.brewer("Egypt", 5, "continuous")[c(2, 3, 1, 4, 5)]
names(colYear) <- seq(2018, 2022)

codeLoc <- 11

plotDC <- function(codeLoc, gradMax = 60, localLevel = "region", mar = c(1, 1, 2.5, 1), cex.main = 1.5, factor.lwd = 1, cex.month = 0.7){
  # codeLoc: geographic numerical code of the locality
  # gradMax: max value of the graduations
  # localLevel: whether the number corresponds to a region, departement
  
  if(localLevel == "region"){
    locName <- dicReg[as.character(codeLoc)]
    # Subset of the data for this locality
    subdat <- dat[dat$nomRegion == locName, ]
  }
  if(localLevel == "departement"){
    locName <- dicDep[codeLoc]
    subdat <- dat[dat$nomDep == locName, ]
  }
  if(localLevel == "other"){
    locName <- ""
    nch <- nchar(codeLoc)
    subdat <- dat[which(substr(dat$COMDOM, 1, nch) == codeLoc), ]
  }
  
  # Aggregate by day
  agg <- aggregate(subdat$LIEUDEC2, by = list(dateDC = subdat$dateDC), FUN = length)
  agg$yearDC <- substr(agg$dateDC, 1, 4)
  
  # Number of days in the year
  agg$nDays <- 365
  agg$nDays[agg$yearDC == 2020] <- 366
  # Date as fraction of the year
  agg$fracYear <- as.numeric((agg$dateDC - as.Date(paste0(agg$yearDC, "-01-01"))) / agg$nDays)
  
  
  # Compute sliding average 
  if(!all(diff(agg$dateDC) == 1)){
    # If we are missing some dates, add them
    dd <- data.frame(dateDC = seq(min(dat$dateDC), max(dat$dateDC), by = "day")) # All days
    agg <- merge(agg, dd, by = "dateDC", all = TRUE) # Add the missing dates, x is NA
    agg[is.na(agg$x), "x"] <- 0 # Set NAs back to 0
  }
  agg$nDC7ave <- sliding.window(agg$x)

  # Get population size
  if(localLevel == "region"){
    pops <- popReg[which(popReg$CodeRegion == codeLoc), ]
  }
  if(localLevel == "departement"){
    pops <- popDep[which(popDep$CodeDep == codeLoc), ]
  }
  if(localLevel == "other"){
    pops <- data.frame(pop2022 = 1, pop2019 = 1)
  }
  pop <- rep(pops$pop2022, nrow(agg)) # Use the 2022 population estimation for 2021 and 2022
  pop[agg$yearDC < 2021] <- pops$pop2019 # Use the 2019 population estimation for 2018, 2019, 2020
  
  # Get point color from year
  agg$col <- colYear[agg$yearDC]
  factor <- ifelse(unique(pop == 1), 1, 10^6)
  pxy <- polar2xy(agg$nDC7ave / pop * factor, agg$fracYear)
  
  # Initialize plot
  par(pty = "s", xpd = FALSE)
  par(mar = mar)
  maxval <- gradMax
  plot(0, type = "n", xlim = c(-maxval, maxval), ylim = c(-maxval, maxval), axes = FALSE, xlab = "", ylab = "")
  
  # Months
  months <- seq(as.Date("2021-01-01"), as.Date("2022-01-01"), by = "month")
  months <- c(months) # Loop
  mnFrac <- as.numeric((months - as.Date(paste0("2021-01-01"))) / 365)
  mxy <- polar2xy(gradMax, mnFrac)
  cols <- rep(c(gray(1), gray(0.95)), 6)
  for(i in 1:12){
    days <- seq(months[i], months[i + 1], by = "day")
    arc <- polar2xy(gradMax, as.numeric(days - as.Date(paste0("2021-01-01"))) / 365)
    polygon(x = c(0, arc$x, 0), 
            y = c(0, arc$y, 0), border = gray(0.95), col = gray(0.9), lwd = factor.lwd * 0.5)
  }
  
  # Month labels
  monthLab <- c("Jan.", "Fév.", "Mars", "Avr.", "Mai", "Juin", "Jui.", "Août", "Sep.", "Oct.", "Nov.", "Déc.")
  orientation <- c(rep(1, 4), rep(0, 4), rep(1, 4)) # angle of the label (other direction for second half of the year)
  r <- gradMax - 5
  thetas <- (1:12)/12 - 0.5/12 # Angles of the months
  for(i in seq_along(monthLab)){
    text(x = r * cos(frac2angle(thetas[i])), y = r * sin(frac2angle(thetas[i])), labels = monthLab[i], srt = 90 + 90 - thetas[i]*360 + orientation[i] * 180, col = gray(0.5), cex = cex.month, family = "sans")
  }
  
  # Graduations
  lwd.grad <- 1
  for(i in seq(10, gradMax, by = 10)){
    cxy <- polar2xy(i, seq(0, 1, length.out = 100))
    lines(cxy$x, cxy$y, type = "l", col = gray(1), lwd = factor.lwd * lwd.grad)
  }
  
  par(xpd = TRUE)
  segments(x0 = head(pxy$x, -1), 
           y0 = head(pxy$y, -1),
           x1 = tail(pxy$x, -1),
           y1 = tail(pxy$y, -1), asp = 1, 
       pch = 16, col = agg$col, lwd = factor.lwd * 1.5)
  
  title(main = locName, cex.main = cex.main, font.main = 1)
} # end plot function

layout(1)
plotDC(11)
plotDC("94", localLevel = "departement", gradMax = 70)

plotDC("24", localLevel = "departement", gradMax = 70, factor.lwd = 0.5)

plotDC("987", localLevel = "other", gradMax = 70, factor.lwd = 0.5)


# Order of the regions (by code)
# in the layout
regions <- c(32, 
             28, 11, 44, 
             53, 24, 27, 
             52, 84, 93, 
             75, 76, 94)

regDROM <- c(1:4, 6)
```

```{r}
addTitlePlot <- function(cexx = 2){
  # Color trick from https://blog.revolutionanalytics.com/2009/01/multicolor-text-in-r.html
  par(mar = rep(0.1, 4), pty = "m")
  plot(0, axes = FALSE, xlab = "", ylab = "", type = "n", xlim = c(-1, 1), ylim = c(-1, 1))

  txt <- "Taux de mortalité en "
  text(0, 0, adj = c(0.5, 0.5), cex = cexx, labels = expression("Taux de mortalité en " * phantom("2018") * ", " * phantom("2019") * ", " * phantom("2020") * ", " * phantom("2021") * ", et " * phantom("2022") * " (partiel)"))
  text(0, 0, adj = c(0.5, 0.5), cex = cexx, labels = expression(phantom("Taux de mortalité en ") * phantom("2018") * phantom(", ") * phantom("2019") * phantom(", ") * phantom("2020") * phantom(", ") * phantom("2021") * phantom(", et ") * phantom("2022") * phantom(" (partiel)")))
  text(0, 0, adj = c(0.5, 0.5), cex = cexx, labels = expression(phantom("Taux de mortalité en ") *"2018" * phantom(", ") * phantom("2019") * phantom(", ") * phantom("2020") * phantom(", ") * phantom("2021") * phantom(", et ") * phantom("2022") * phantom(" (partiel)")), col = colYear["2018"])
  text(0, 0, adj = c(0.5, 0.5), cex = cexx, labels = expression(phantom("Taux de mortalité en ") * phantom("2018") * phantom(", ") *"2019" * phantom(", ") * phantom("2020") * phantom(", ") * phantom("2021") * phantom(", et ") * phantom("2022") * phantom(" (partiel)")), col = colYear["2019"])
  text(0, 0, adj = c(0.5, 0.5), cex = cexx, labels = expression(phantom("Taux de mortalité en ") * phantom("2018") * phantom(", ") * phantom("2019") * phantom(", ") *"2020" * phantom(", ") * phantom("2021") * phantom(", et ") * phantom("2022") * phantom(" (partiel)")), col = colYear["2020"])
  text(0, 0, adj = c(0.5, 0.5), cex = cexx, labels = expression(phantom("Taux de mortalité en ") * phantom("2018") * phantom(", ") * phantom("2019") * phantom(", ") * phantom("2020") * phantom(", ") *"2021" * phantom(", et ") * phantom("2022") * phantom(" (partiel)")), col = colYear["2021"])
  text(0, 0, adj = c(0.5, 0.5), cex = cexx, labels = expression(phantom("Taux de mortalité en ") * phantom("2018") * phantom(", ") * phantom("2019") * phantom(", ") * phantom("2020") * phantom(", ") * phantom("2021") * phantom(", et ") *"2022" * " (partiel)"), col = colYear["2022"])
}
```


### Mainland 

```{r DCRegMainland}
fname.RegFra <- "pics/INSEE_DC_regions.png"
fac <- 2.5 # Multiplying factor for the png output
hh <- 0.2 # Height of the title and credits lines

png(fname.RegFra, width = fac*3, height = fac*(5+2*hh), units = "in", res = 300)

layout(matrix(c(rep(16, 3), 2, 3, 2, 4:15, rep(17, 3))-2, byrow = TRUE, ncol = 3), heights = c(hh, rep(1, 5), 0.2)) # plot layout as grid
# layout.show(15)

# For each region, plot DC figures
for(codereg in regions){
  par(pty = "s", xpd = FALSE) # Square aspect ratios
  par(mar = c(0, 0, 1.5, 0) + 1)
  plotDC(codereg)
#  plot(0, axes = FALSE, xlab = "", ylab = "")
#  title(dicReg[as.character(codereg)], cex.main = 1.5, font.main = 1)
}

addTitlePlot()

par(mar = rep(0.2, 4), pty = "m")
plot(0, axes = FALSE, xlab = "", ylab = "", type = "n", xlim = c(-1, 1), ylim = c(-1, 1))
text(-1, 1, adj = c(0, 1), labels = "Les graduations vont de 10 en 10, en décès quotidiens par 1 million d'habitants (lissage 7 jours)
Données: INSEE mars 2022, https://www.insee.fr/fr/statistiques/4487988?sommaire=4487854\nCode: https://github.com/flodebarre/covid_indicateurs/blob/main/mortaliteINSEE.Rmd", family = "mono", cex = 1, col = gray(0.5))

dev.off()
system(paste0("open ", fname.RegFra))

```

### DROM

```{r DCRegDROM}
fname.DROM <- "pics/INSEE_DC_DROM.png"

ech <- c(120, 120, 60, 60, NA, 60) # Scale for max graduation

png(fname.DROM, width = fac*3, height = fac*(3+2*hh), units = "in", res = 300)

layout(matrix(c(6, 0, 0, 0, 7, 6, 1, 2, 3, 7, 6, 0, 4, 5, 7, 6, 0, 0, 0, 7), byrow = FALSE, ncol = 4), heights = c(hh, rep(1, 3), 0.2), widths = c(0.5, 1, 1, 0.5)) # plot layout as grid
layout.show(7)

# For each region, plot DC figures
for(codereg in regDROM){
  par(pty = "s", xpd = FALSE) # Square aspect ratios
  par(mar = c(0, 0, 1.5, 0) + 1)
  plotDC(codereg, gradMax = ech[codereg])
#  plot(0, axes = FALSE, xlab = "", ylab = "")
#  title(dicReg[as.character(codereg)], cex.main = 1.5, font.main = 1)
}

addTitlePlot()

par(mar = rep(0.2, 4), pty = "m")
plot(0, axes = FALSE, xlab = "", ylab = "", type = "n", xlim = c(-1, 1), ylim = c(-1, 1))
text(-1, 1, adj = c(0, 1), labels = "Les graduations vont de 10 en 10, en décès quotidiens par 1 million d'habitants (lissage 7 jours)
Données: INSEE mars 2022, https://www.insee.fr/fr/statistiques/4487988?sommaire=4487854\nCode: https://github.com/flodebarre/covid_indicateurs/blob/main/mortaliteINSEE.Rmd", family = "mono", cex = 1, col = gray(0.5))

dev.off()
system(paste0("open ", fname.DROM))

```

## By departement

```{r mapDepDC}
geo.departements <- read.csv("data/departements-france.csv")
source("../data/layout_departements.R")

fname.DepFra <- "pics/INSEE_DCdepartements.png"
fac.dep <- 1
png(filename = fname.DepFra, width = fac.dep * sum(widths.deps), height = fac.dep * sum(heights.deps), res = 300, units = "in")

emptyplot <- function(){
  plot(0, 0, type = "n", axes = FALSE, xlab = "", ylab = "")
}

# par(bg = gray(0.3), fg = "white")

# Plot layout, placing each departement approximately where it is on the French map
layout(deps.indices, heights = heights.deps, widths = widths.deps)

i <- 1
for(i in geo.departements$index){
  dep <- geo.departements[i, "code_departement"]
  print(i)
  plotDC(codeLoc = dep, localLevel = "departement", gradMax = 90, mar = c(0.1, 0.1, 0.5, 0.1), cex.main = 0.9, factor.lwd = 0.4, cex.month = 0.4)
  #par(mar = rep(0.1, 4)); emptyplot()
}


# Legend
emptyplot()

# Title
addTitlePlot(cexx = 3)


# Credits
par(mar = rep(0.2, 4), pty = "m")
plot(0, axes = FALSE, xlab = "", ylab = "", type = "n", xlim = c(-1, 1), ylim = c(-1, 1))
text(-1, 1, adj = c(0, 1), labels = "Les graduations vont de 10 en 10, en décès quotidiens par 1 million d'habitants (lissage 7 jours)
Données: INSEE mars 2022, https://www.insee.fr/fr/statistiques/4487988?sommaire=4487854\nCode: https://github.com/flodebarre/covid_indicateurs/blob/main/mortaliteINSEE.Rmd", family = "mono", cex = 1.5, col = gray(0.5))

dev.off()
system(paste0("open ", fname.DepFra))

```

## Single departements

```{r}
# Choice of departement with constrasted dynamics
# (alternative: use geo.departements$nom_departement to do them all)

for(depName in c("Ille-et-Vilaine", "Haut-Rhin", "Guadeloupe", "Savoie")){
  
  hl <- 0.15 # Height of the other sections of the figure
  
  # Get departement code
  dep <- geo.departements[geo.departements$nom_departement == depName, "code_departement"]
  
  fname <- paste0("pics/INSEE_DC_", dep, "_departements.png")
  
  fac.dep <- 5 # factor for the size of the picture
  png(filename = fname, width = fac.dep * 1.2, height = fac.dep * (2*hl + 1), res = 300, units = "in")
  
  layout(matrix(c(2, 1, 3), ncol = 1), heights = c(hl, 1, hl))
  
  # Main plot
  plotDC(codeLoc = dep, localLevel = "departement", gradMax = 90, mar = c(1, 1, 2.5, 1), cex.main = 1.75, factor.lwd = 1, cex.month = 0.8)
  
  # Title
  addTitlePlot(cexx = 1.75)
  
  # Credits
  par(mar = rep(0.2, 4), pty = "m")
  plot(0, axes = FALSE, xlab = "", ylab = "", type = "n", xlim = c(-1, 1), ylim = c(-1, 1))
  text(-1, 1, adj = c(0, 1), labels = "Les graduations vont de 10 en 10, en décès quotidiens par 1 million d'habitants (lissage 7 jours)
Données: INSEE mars 2022, https://www.insee.fr/fr/statistiques/4487988?sommaire=4487854\nCode: https://github.com/flodebarre/covid_indicateurs/blob/main/mortaliteINSEE.Rmd", family = "mono", cex = 0.8, col = gray(0.5))
  
  dev.off()
  system(paste0("open ", fname))
}

```



```{r}
# Save outputs
system(paste0("git add -f ", fname.RegFra))
system(paste0("git add -f ", fname.DROM))
system(paste0("git add -f ", fname.DepFra))

system("git commit -m 'load figures INSEE DC'")
system("git push")
```

## Special requests

```{r}
# Are there data from COMs?
# Code geo COM: https://www.insee.fr/fr/information/2028040

# Where people live
any(substr(dat$COMDOM, 1, 3) == "987")
dat[which(substr(dat$COMDOM, 1, 2) == "98"), ]

# Where people died
any(substr(dat$COMDEC, 1, 3) == "987")
any(substr(dat$COMDEC, 1, 2) == "98")

sum(substr(dat$COMDEC, 1, 4) == "9750")

# -> no data on deaths that took place in COM 
```

