---
title: "phasePlots"
author: "FD"
output: 
  html_document:
    self_contained: no
    keep_md: true
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Initializations

```{r}
dlData <- FALSE # Whether to download the data
```

```{r}
source("usefulFunctions.R")
```

```{r}
library("colorspace")
library("MetBrewer")
library("mapsf")
```

# Load data

Source: <https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/#>, `sp-pos-quot-` files

```{r loadData}
URL.Fra <- "https://www.data.gouv.fr/fr/datasets/r/dd0de5d9-b5a5-4503-930a-7b08dc0adc7c"
URL.Reg <- "https://www.data.gouv.fr/fr/datasets/r/001aca18-df6a-45c8-89e6-f82d689e6c01"
URL.Dep <- "https://www.data.gouv.fr/fr/datasets/r/406c6a23-e283-4300-9484-54e78c8ae675"

fileFra <- "data/cases_France.csv"
fileReg <- "data/cases_Reg.csv"
fileDep <- "data/cases_Dep.csv"

if(dlData){
  download.file(URL.Fra, fileFra)
  download.file(URL.Reg, fileReg)
  download.file(URL.Dep, fileDep)
  
  system("git add data/cases_*")
  system("git commit -m 'Update data daily cases'")
}

# Load files
datFra <- read.csv(fileFra, sep = ";")
datReg <- read.csv(fileReg, sep = ";")
datDep <- read.csv(fileDep, sep = ";")
```


```{r addGeographicInfo}
# Add geographic information
geo.regions <- read.csv("data/coderegions.csv")
datReg <- merge(datReg, geo.regions, by.x = "reg", by.y = "code_region", all.x = TRUE)

geo.departements <- read.csv("data/departements-france.csv")
# Add index to have consecutive values for all departements
geo.departements$index <- 1:nrow(geo.departements)
datDep <- merge(datDep, geo.departements, by.x = "dep", by.y = "code_departement", all = TRUE)

# Sort by date!
datReg <- datReg[order(datReg$jour), ]
datDep <- datDep[order(datDep$jour), ]

```


Load and assign jours feries
Source: <https://www.data.gouv.fr/en/datasets/jours-feries-en-france/>

```{r}
feries <- read.csv("data/jours_feries_metropole.csv")

datFra$ferie <- is.element(datFra$jour, feries$date)
datReg$ferie <- is.element(datReg$jour, feries$date)
datDep$ferie <- is.element(datDep$jour, feries$date)
```

## Define colors

```{r}
colReg <- rev(met.brewer("Signac", n = 13, type = "continuous"))
names(colReg) <- geo.regions[geo.regions$code_region > 10, "nom_region"]
```


# Ratios

Define color scale

```{r}
nn <- 100 # Number of values
x1 <- sequential_hcl(nn/2, "Inferno")
x2 <- sequential_hcl(nn/2, "BluYl")
colorScale <- rev(c(x1, rev(x2)))

```


```{r}
par(bg = "white", 
      fg = "black", 
      col.axis = "black", col.lab = "black")

plotRatio <- function(dates, vals, ylim = NA, xlim = NA, 
                      colScale = colorScale, 
                      cex = 1, axesLabels = TRUE, lightAxes = FALSE, 
                      bfg = NA, showGraduations = TRUE){
  # dates: vector of date values, as dates
  # vals: vector of values
  # ylim: y range
  # xlim: x range
  # colScale: color scale for the plots
  # cex: cex
  # axesLabels: boolean, whether to plot axes labels
  # lightAxes: whether to plot light version of the axes
  # bfg: background color and foreground color
    
  # Check that we have data for consecutive dates
  stopifnot(all(diff(dates) == 1))
  # When it's OK we can just go on
  # Check that both vectors have the same length
  stopifnot(length(dates) == length(vals))
  
  # Remove jours feries
  iferie <- which(is.element(dates, as.Date(feries$date)))

  vals[iferie] <- NA
  
  # Index of the final line
  nend <- length(vals)
  
  ratios7 <- rep(NA, nend) # Initialize output
  
  # Ratios
  ratios7[8:nend] <- vals[8:nend] / vals[1:(nend - 7)]

  # Sliding average of the ratio (centered)
  ratios7.slidingave <- sliding.window(ratios7, pos = 4, winwdt = 7)
  
  # Define range of values
  if(length(ylim) <= 1){
    ylim <- range(ratios7, na.rm = TRUE)
  }
  
  if(length(xlim) <= 1){
    xlim <- range(dates, na.rm = TRUE)
  }
  
  fgg <- "black"
  if(!is.na(bfg)){
      fgg <- bfg[2]
  par(bg = bfg[1], 
      fg = bfg[2], 
      col.axis = fgg, col.lab = fgg)
  }
  
  par(las = 1)


  # Initialize figure
  plot(dates, ratios7, ylim = ylim, xlim = xlim, 
       log = "y", axes = FALSE, 
       xlab = "", ylab = "cas(j)/cas(j-7), échelle log", 
       type = "n")
  
  par(xpd = FALSE)
  
  abline(h = 1, lwd = 2, col = fgg) # No change line

  if(showGraduations){
    # Plot doubling times
    for(i in c(1, 2, 4)){
      t <- log(2) / i
      op <- 0.25
      abline(h = exp(t), col = adjustcolor(fgg, op), lwd = 1)
      abline(h = exp(-t), col = adjustcolor(fgg, op), lwd = 1)
    }
  }
  
  # Add axes
  tckk <- -0.02
  cexx <- 0.8 * cex
  cexx2 <- cexx
  days <- seq(min(dates), max(dates), by = "day")
  months <- seq(as.Date("2020-03-01"), max(dates)+30, by = "month")
  limPlot <- par("usr") # limits of the plot in user coordinates
  
  if(diff(range(dates)) > 150 | lightAxes){
    dateFormat <- ifelse(lightAxes, "%b", "%b %Y")
    adj <- 0
  }else{
    dateFormat <- "%d/%m"
    adj <- 0.5
    
    if(axesLabels){
      # Ticks every day
      axis(1, at = days, labels = rep("", length(days)), las = 3, cex.axis = cexx, tck = tckk/2, lwd = 0, lwd.ticks = 1, pos = ylim[1])
    
    # Mid-month
    axis(1, at = months + 14, labels = format(months + 14, format = dateFormat), las = 1, cex.axis = cexx2, tck = tckk, lwd = 0, lwd.ticks = 1, pos = ylim[1])
    }
  }
  
  # Month ticks
  if(axesLabels){
    # With labels
    axis(1, at = months, labels = format(months, format = dateFormat), las = 1, cex.axis = cexx2, tck = tckk, lwd = 0, lwd.ticks = 1, pos = ylim[1])
    
    axis(2, at = c(seq(0.1, 1, by = 0.1), seq(1.2, 3, by = 0.2)), tck = -.01, pos = as.Date(limPlot[1], origin = "1970-01-01"), cex.axis = cexx)

  }
  
  
  #............................................
  # Define colors
  maxVal <- ceiling(max(abs(log(ylim)))*10)/10 # max value for the scale
  logvals <- seq(-maxVal, maxVal, length.out = length(colScale))
  icols <- cut(log(ratios7), breaks = logvals, labels = FALSE)
  jcols <- cut(log(sliding.window(ratios7)), breaks = logvals, labels = FALSE)
  
  #...........................................
  par(xpd = TRUE)
  # Sliding average
  lines(dates, ratios7.slidingave, col = "black", cex = cex)

  # Plot points  
  points(as.Date(dates), ratios7, col = colScale[icols], pch = 16, cex = cex)

  # Just last point, bigger
  points(dates[nend], ratios7[nend], col = colScale[icols[nend]], pch = 16, cex = 2*cex)
  par(xpd = FALSE)
  
  # Output
  list(ratios7 = ratios7, colEnd = colScale[icols[nend]])
  
}

unique(datReg$reg)
tmp <- datReg[datReg$reg == 11 & datReg$cl_age90 == 0 & datReg$jour >= "2021-12-25", ]
head(tmp)

par(new = FALSE)
par(mar = c(4, 6, 3, 1))
plotRatio(as.Date(tmp$jour), tmp$P)
# text(as.Date(min(dates)), 0.7, "Les cas augmentent")
# mtext("dd\n1.0\ndd", side = 2, line = 0, adj = c(1, 0.5))
# axis(2, col = "red")



```

## Ratios regions

```{r compareRegions, fig.width=9, fig.height=12}

palH <- rev(met.brewer("Hiroshige", n = 101, type = "continuous"))

plotRegion <- function(region){
  tmp <- datReg[which(datReg$nom_region == region & datReg$cl_age90 == 0 & datReg$jour >= "2021-12-25"), ]
  par(mgp = c(2.5, 0.5, 0), mar = c(4, 3, 3, 1))
  plotRatio(as.Date(tmp$jour), tmp$P, ylim = c(0.35, 3), lightAxes = TRUE, colScale = palH
)
  title(main = region)
}


layout(matrix(1:15, ncol = 3, byrow = TRUE))
par(las = 1)

# 1 Plot legend (no)
par(mar = c(0, 0, 0, 0))
plot(0, 0, xlab = "", ylab = "", type = "n", axes = FALSE, xlim = c(-0.2, 1), ylim = c(-1, 0.5))


# 2 HDF
#layout(1)
marplot <- c(2, 2, 2, 2)
par(mar = marplot)
plotRegion("Hauts-de-France")


# 3 Plot credits
par(mar = c(0, 0, 0, 0))
plot(0, 0, xlab = "", ylab = "", type = "n", axes = FALSE, xlim = c(-0.1, 1), ylim = c(-1, 1))
text(0, 0, paste0("@flodebarre, ", Sys.Date(), "

Data:
https://www.data.gouv.fr/fr/datasets/
donnees-relatives-aux-resultats-des-
tests-virologiques-covid-19/

Code: https://github.com/flodebarre/
covid_indicateurs/blob/main/phasePlots.Rmd
"), adj = 0, cex = 0.6, family = "mono")

par(mar = marplot)

# 4 NOR
plotRegion("Normandie")

# 5 IDF
plotRegion("Île-de-France")

# 6 GE
plotRegion("Grand Est")

# 7 BRE
plotRegion("Bretagne")

# 8 CVL
plotRegion("Centre-Val de Loire")

# 9 BFC
plotRegion("Bourgogne-Franche-Comté")

# 10 PDL
plotRegion("Pays de la Loire")

# 11 ARA
plotRegion("Auvergne-Rhône-Alpes")

# 12 PACA
plotRegion("Provence-Alpes-Côte d'Azur")

# 13 NAQ
plotRegion("Nouvelle-Aquitaine")

# 14 OCC
plotRegion("Occitanie")

# 15 COR
plotRegion("Corse")

```


```{r eval = FALSE}
layout(matrix(1:(12*15), nrow = 15))
par(mar = c(0.1, 0.1, 0.1, 0.1), cex = 0.5)

for(i in unique(datDep$dep)){
    tmp <- datDep[which(datDep$dep == i & datDep$cl_age90 == 9 & datDep$jour >= "2021-12-25"), ]
  par(mgp = c(1, 0.2, 0), mar = 0.5*c(0.5, 0.5, 1, 0.5))
  plotRatio(as.Date(tmp$jour), tmp$P, ylim = c(0.35, 3), axesLabels = TRUE, cex = 0.9, lightAxes = TRUE)
title(main = i)
}

```

## Ratios Departements

Dynamics of the ratio of cases, by departement.

```{r compareDepartements, fig.height=12, fig.width=10, dpi = 300}
source("../data/layout_departements.R")

minDate <- "2021-12-25"

fname <- "pics/casesRatios_departements.png"
png(filename = fname, width = 10, height = 13, res = 500, units = "in")


par(bg = gray(0.3), fg = "white")

# Plot layout, placing each departement approximately where it is on the French map
layout(deps.indices, heights = heights.deps, widths = widths.deps)

i <- 1
for(i in geo.departements$index){
  dep <- geo.departements[i, "code_departement"]

  tmp <- datDep[which(datDep$dep == dep &
                        datDep$cl_age90 == 0 &
                        datDep$jour >= "2021-12-25"), ]
  par(mgp = c(2.5, 0.5, 0), mar = c(0.5, 0, 1, 0)+0.25)
#  plot(0)
  pR <- plotRatio(as.Date(tmp$jour), tmp$P, ylim = c(0.35, 3), axesLabels = FALSE, cex = 0.6, lightAxes = TRUE, colScale = palH, showGraduations = FALSE, bfg = c(par()$bg, par()$fg))
  title(main = geo.departements[i, "nom_departement"], cex.main = 0.7, col.main = pR$colEnd, font.main = 1)


  }

emptyplot <- function(){
  plot(0, 0, type = "n", axes = FALSE, xlab = "", ylab = "")
}

# Legend
dep <- "75"
 tmp <- datDep[which(datDep$dep == dep & 
                         datDep$cl_age90 == 0 & 
                         datDep$jour >= "2021-12-25"), ]
  par(mgp = c(0.5, 0.1, 0), mar = c(0, 0, 1.25, 0))
  plotRatio(as.Date(tmp$jour), tmp$P, ylim = c(0.35, 3), axesLabels = TRUE, cex = 0.7, lightAxes = TRUE, colScale = palH, bfg = c(par()$bg, par()$fg), showGraduations = FALSE)
  title(main = "Graduations \ndes figures", cex.main = 0.75, col.main = par()$fg, font.main = 1)


emptyplot()
text(0, 0, paste0("Ratios des nombres de cas d'une semaine à l'autre (échelle log), \n", format(as.Date(minDate) + 7, "%d/%m/%Y"), " -- ", format(as.Date(max(datDep$jour)), "%d/%m/%Y")), adj = 
c(0.5, 0.5), cex = 1.5)


emptyplot()
  limPlot <- par("usr") # limits of the plot in user coordinates
text(limPlot[1], 0, paste0("@flodebarre, ", Sys.Date(), 
                           ". Inspiré des figures de @BristOliver et de la carte des Décodeurs du Monde https://tinyurl.com/carteFRDecLM", 
                           "\n", 
                  "Data: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/#
Code: Code: https://github.com/flodebarre/covid_indicateurs/blob/main/phasePlots.Rmd"), cex = 0.8, family = "mono", adj = c(0, 0.5), col = adjustcolor(par()$fg, 0.7) )


dev.off()
system(paste0("open ", fname))

```


```{r test, fig.height=12, fig.width=10, eval = FALSE}
layout.show(104)
for(i in 1:101){
  plot(0, 0, type = "n")
  text(0,0, i)
}
# Legend
dep <- "75"
 tmp <- datDep[which(datDep$dep == dep & 
                         datDep$cl_age90 == 0 & 
                         datDep$jour >= "2021-12-25"), ]
  par(mgp = c(0.5, 0.1, 0), mar = c(0, 0, 1, 0))
  plotRatio(as.Date(tmp$jour), tmp$P, ylim = c(0.35, 3), axesLabels = TRUE, cex = 0.7, lightAxes = TRUE, colScale = palH)
    title(main = "Légende", cex.main = 0.8, col.main = par()$fg, font.main = 1)


emptyplot()
text(0, 0, "xx")
text(0, 0, paste0("Ratios des cas d'une semaine à l'autre, ", minDate, " -- ", max(datDep$jour)), adj = 
c(0.5, 0.5), cex = 1.5)


emptyplot()
  limPlot <- par("usr") # limits of the plot in user coordinates
text(limPlot[1], 0, paste0("@flodebarre, ", Sys.Date(), "\n", 
                  "Data: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/#
Code: Code: https://github.com/flodebarre/covid_indicateurs/blob/main/phasePlots.Rmd"), cex = 0.7, family = "mono", adj = c(0, 0.5), col = gray(0.4))

```



# Map departements

```{r}
# Load map 
load("../data/mapFiles_withDepReg.RData")
depsMetro <- geo.departements[1:96, "code_departement"]

par(fg = "black", bg = "white")
```

```{r, eval = FALSE}
minDate <- "2022-01-01"
theageclass <- 0

thedate <- "2022-03-03"
ylim <- c(0.5, 3)

palH <- rev(met.brewer("Hiroshige", n = 101, type = "continuous"))

palH2 <- rev(met.brewer("Hiroshige", n = 13, type = "continuous"))
maxVal <- ceiling(max(abs(log(ylim)))*10)/10 # max value for the scale
logvals <- seq(-maxVal, maxVal, length.out = length(palH))
vals2 <- round(exp(seq(-maxVal, maxVal, length.out = length(palH2))), 2)


# Function to plot map at a given date
plotMapDep <- function(thedate){
  
  if(!any(is.element(c(thedate, as.Date(thedate, origin = "1970-01-01") - 7), as.Date(feries$date)))){
    
    thedate <- as.Date(thedate, origin = "1970-01-01")
    cat(thedate)
    
    fname <- paste0("pics/Ratio7Dep_", thedate, "_clage-", theageclass, ".png")
    
    mf_export(x = mdeps.metro, export = "png", 
              filename = fname, width = 850, height = 800,
              res = 90
    )
    
    
    
    tmp1 <- datDep[datDep$jour == thedate & datDep$cl_age90 == 0 & is.element(datDep$dep, depsMetro), ]
    tmp2 <- datDep[datDep$jour == as.character(as.Date(thedate) - 7) & datDep$cl_age90 == 0 & is.element(datDep$dep, depsMetro), ]
    
    tmp1 <- tmp1[order(tmp1$dep), c("dep", "P")]
    tmp2 <- tmp2[order(tmp2$dep), c("dep", "P")]
    
    tmp1$ratio7 <- tmp1$P / tmp2$P
    tmp <- merge(mdeps, tmp1, by.y = "dep", by.x = "code_insee")
    tmp$logratio7 <- log(tmp$ratio7)
    
    
    layout(1)
    mf_theme(bg = par()$bg)
    mf_init(tmp, expandBB = c(0.05, 0, 0.125, -0.2))
    mf_map(tmp, var = "logratio7",
           type = "choro", breaks = logvals, pal = palH, leg_pos = "n", add = TRUE)
    
    mf_legend_c(pos = "left", val = vals2, pal = palH2, title = "Ratio du nombre de cas \nd'une semaine à l'autre\n(échelle log)")
    
    mf_map(mregions, add = TRUE, col = gray(0, 0), lwd = 1)
    mf_title(txt = paste0("Ratio du nombre de cas d'une semaine à l'autre, au ", format(as.Date(thedate), "%d/%m/%Y")), bg = par()$bg, fg = par()$fg, cex = 1.5)
    
    
    mf_credits(paste0("@flodebarre, ", Sys.Date(), "\n", 
                      "Données cas : https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/#\n",
                      "Fond de carte : © les contributeurs d'OpenStreetMap sous licence ODbL. Carte réalisée avec le package ",
                      "mapsf ",
                      packageVersion("mapsf")), cex = 0.8)
    
    
    
    mar.inset <- c(0, 0, 0.8, 0) # Margins of the inset
    line.title.2 <- 0.2 # Line position of the inset titles, communes
    
    # Petite couronne
    mf_inset_on(fig = c(0.825, 0.95, 0.8, 0.95) - 0.05 * c(0, 0, 1, 1))
    tmpP <- tmp[is.element(tmp$code_insee, c("75", "92", "93", "94")),]
    mf_theme(mar = mar.inset)
    mf_init(tmpP, expandBB = c(0, 0, 0, 0))
    mf_map(tmpP, var = "logratio7", type = "choro", breaks = logvals, pal = palH, leg_pos = "n", add = TRUE)
    mf_title("Petite couronne", tab = TRUE, inner = FALSE, line = 0.5, cex = 0.8, bg = gray(0, 0), fg = par()$fg)
    box()
    mf_inset_off()
    
    mf_inset_on(fig = c(0, 0.35, 0.725, 0.98))
    subFra <- datFra[which(datFra$jour >= as.Date(minDate) - 7 & datFra$cl_age90 == theageclass & datFra$jour <= thedate), c("jour", "P")]
    par(mar = c(2, 2, 1, 0.5), cex.lab = 0.7, mgp = c(3, 0.25, 0))
    plotRatio(as.Date(subFra$jour), subFra$P, colScale = palH, xlim = c(as.Date(minDate), Sys.Date() - 3), ylim = ylim)
    title("France entière", font.main = 1, cex.main = 1)
    cext <- 0.75
    colt <- gray(0.5)
    text(as.Date(minDate), y = 0.6, labels = "Le nb de cas diminue", cex = cext, adj = c(0, 0.5), col = colt)
    text(as.Date(minDate), y = 2.6, labels = "Le nb de cas augmente", cex = cext, adj = c(0, 0.5), col = colt)
    mf_inset_off()
    
    dev.off()
  } # end if ferie
}


# Plot the last one
plotMapDep(max(datDep$jour))


```

Animation 

```{r, eval = FALSE}
for(thedate in seq(as.Date(minDate), as.Date(max(datDep$jour)), by = "day")){
  plotMapDep(thedate)
  
} # end loop date

# system(paste0("open ", fname))

# Copy the last one to freeze the gif
for(icopy in 1:10){
  system(paste0("cp ", substr(fname, 1, nchar(fname) - 4), "_", icopy, ".png"))
}

# Convert into movie
system("rm pics/mapRatio7Dep.mp4")
system(paste0("ffmpeg -pattern_type glob -i 'pics/Ratio7Dep_", "*", ".png' -vcodec libx264 -s 850x800 -pix_fmt yuv420p -filter:v 'setpts=8.0*PTS' pics/mapRatio7Dep.mp4"))



```

# Phase plot

## Departements

```{r}
minDate <- "2022-01-01"
agCl <- 0

dInitDate <- 14
tmpDep <- datDep[which(datDep$jour >= as.Date(minDate) - dInitDate & datDep$cl_age90 == agCl), ]
```

```{r phasePlotDep_FunctionDefinition, fig.width=10.66, fig.height=6}
endDates <- seq(as.Date(minDate), as.Date(max(tmpDep$jour)), by = "day")

maxOp <- 0.7
ops <- maxOp * seq(0, 1, length.out = nrow(tmpDep)/length(unique(tmpDep$dep)))^2 # Opacity values

plotPhaseDep0 <- function(idate){
  endDate <- endDates[idate] # Get the corresponding date
  
  # Subselect the data until this date
  tmpp <- tmpDep[tmpDep$jour <= endDate, ]
  
  # Define output figure
  fname <- paste0("pics/phaseDep_", formatC(idate, width=3, flag="0"), ".png")
  png(fname, width = 10.6, height = 6, units = "in", res = 300)
  
  layout(matrix(1:2, ncol = 2), widths = c(5, 1.25))
  
  par(mar = c(4.5, 3, 2, 0), las = 1, mgp = c(1.5, 0.3, 0), tck = -0.01, bg = gray(1), cex.axis = 0.8)

  # Initialize plot
  plot(1, type = "n", xlim = c(100, 5000), ylim = c(0.4, 4), log = "xy", 
       xlab = "7-day incidence per 100'000 inhabitants", ylab = "week-to-week ratio of 7-day incidence (log scale)")
  abline(h = 1, lwd = 2)
  limPlot <- par("usr")
  
  mtext(side = 1, text = paste0("@flodebarre, ", Sys.Date(), ", inspired by @trvrb, @BristOliver, @VictimOfMaths
Data: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/
Code: https://github.com/flodebarre/covid_indicateurs/blob/main/phasePlots.Rmd
"), adj = 0, cex = 0.5, family = "mono", line = 3.75, col = gray(0.4))
  
  
  for(i in geo.departements$code_departement[nchar(geo.departements$code_departement) < 3]){
    reg <- geo.departements[geo.departements$code_departement == i, "nom_region"]
    
    # Subset of the data for this dep
    sub <- tmpDep[which(tmpp$dep == i), ]
    
    stopifnot(all(diff(as.Date(sub$jour)) == 1))
    
    iferie <- which(is.element(sub$jour, feries$date))
    sub[iferie, "P"] <- NA
    
    # Index of the final line
    nend <- length(sub$P)
    ratios7 <- rep(NA, nend) # Initialize output
    # Ratios
    ratios7[8:nend] <- sub$P[8:nend] / sub$P[1:(nend - 7)]
    
    
    sum7 <- sliding.window(sub$P, pos = 7, FUN = sum)
    incid7 <- sum7 / sub$pop * 10^5
    
    ratioIncid7 <- rep(NA, nend)
    ratioIncid7[8:nend] <- incid7[8:nend] / incid7[1:(nend - 7)]
    
    # Find points which are not NAs (to avoid interruptions)
    inna <- which(!is.na(incid7) & !is.na(ratios7))

    segments(x0 = head(incid7[inna], -1), 
             y0 = head(ratioIncid7[inna], -1), 
             x1 = tail(incid7[inna], -1), 
             y1 = tail(ratioIncid7[inna], -1), 
             col = vapply(tail(ops, (length(inna) - 1)), function(op) adjustcolor(colReg[reg], op), FUN.VALUE = "x")
    )
    
#    lines(incid7[inna], ratioIncid7[inna], col = adjustcolor(colReg[reg], op), type = "l")
    
    # Point at the final date to identify the departement
    points(x = incid7[nend], y = ratioIncid7[nend], col = adjustcolor(colReg[reg], maxOp), cex = 2, pch = 16)
    
    # Add departement number in the final point
    text(x = incid7[nend], y = ratioIncid7[nend], col = "white", cex = 0.45, labels = i, adj = c(0.5, 0.5))
    
    
  }
  
  title(main = paste0("Covid-19 cases by départements, France, ", sub$jour[nend]))
  colT <- gray(0.5)
  text(x = 10^(limPlot[1]), y = 10^(limPlot[3]), adj = c(-0.1, -1), labels = "Cases decrease ←", col = colT)
  text(x = 10^(limPlot[1]), y = 10^(limPlot[4]), adj = c(-0.1, 2), labels = "Cases increase →", col = colT)
  
  #..........................
  xlm <- c(-0.1, 2)
  
  par(mar = c(4, 0, 4, 0))
  dy <- 6
  plot(0, type = "n", axes = FALSE, xlab = "", ylab = "", xlim = xlm, ylim = c(1 - dy, length(colReg)+dy))
  
  i <- 1
  nomsregs <- names(colReg)
  for(reg in nomsregs){
    text(x = 0, y = length(nomsregs) - i + 1, labels = reg, col = colReg[reg], adj = c(0, 0.5), cex = 0.8)
    i <- i + 1
  }
  dev.off()
  
}

# Plot last picture
plotPhaseDep0(length(endDates))

```


```{r phasePlotDep, fig.width=10.66, fig.height=6}
length(endDates)
system("rm pics/phaseDep_*")
for(iD in seq_along(endDates)){
  print(iD)
  plotPhaseDep0(iD)
}

# Copy the last one to put it as first one (opening picture)
system(paste0("cp ", "pics/phaseDep_", formatC(iD, width=3, flag="0"), ".png", " ",  "pics/phaseDep_000.png"))

# Copy last pic
for(j in 1:20){
  system(paste0("cp pics/phaseDep_", formatC(iD, width=3, flag="0"), ".png", " pics/phaseDep_", formatC(iD, width=3, flag="0"), "_", j, ".png"))
}

# Copy first one
for(j in 1:5){
  system(paste0("cp pics/phaseDep_000.png", " pics/phaseDep_000_", j, ".png"))
}

# Convert into movie
system("rm pics/mapPhasePlotDep.mp4")
system(paste0("ffmpeg -pattern_type glob -i 'pics/phaseDep_", "*", ".png' -vcodec libx264 -s 800x450 -pix_fmt yuv420p -filter:v 'setpts=5.0*PTS' pics/mapPhasePlotDep.mp4"))


#system(paste0("open ", fname))
```


