---
title: "taux croissance"
author: "FD"
output: 
  html_document:
    self_contained: false
---

This code produces a version of Oliver Johnson's case ratio figures for French data  
<https://twitter.com/BristOliver/status/1462112681956200458?s=20>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
rm(list = ls()) # I don't care, I code the way I want, and I like it this way
```

# Initializations

```{r}
# Whether to download the data
dlData <- TRUE 
```

```{r}
# Color packages
library("RColorBrewer")
library("colorspace")

# Colors for days
colJ <- brewer.pal(n = 7, name = "Set2")
names(colJ) <- 1:7

```

```{r}
source("usefulFunctions.R")
```


```{r}
# Function to make color transparent
makeTransparent = function(color, alpha = 0.5) {
  if(alpha<0 | alpha>1) stop("alpha must be between 0 and 1")
  newcol <- col2rgb(col=color, alpha = FALSE)
  return(rgb(red = newcol[1], green = newcol[2], blue = newcol[3], alpha = 255*alpha, maxColorValue=255))
}
```

# Load data

Source: <https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/#>, `sp-pos-quot-fra-xxx.csv`

```{r}
URL <- "https://www.data.gouv.fr/fr/datasets/r/dd0de5d9-b5a5-4503-930a-7b08dc0adc7c"

dataFile <- paste0("data/FranceCas.csv") # name file with today's date
if(dlData){
  download.file(URL, dataFile) # download file
}

dat.France <- read.csv(dataFile, sep = ";", stringsAsFactors = FALSE)


```

Add info on dates

```{r}
# Add weekday
weekday <- format(as.Date(dat.France$jour), "%w")
# Sunday is 0, set it as 7
weekday[weekday == 0] <- 7
dat.France$weekday <- weekday

# Add week number
weeknb <-  format(as.Date(dat.France$jour), "%W")
# Set 00 and 52 equal
weeknb[weeknb == "00"] <- "52"
dat.France$weeknb <- weeknb
```

Load and assign jours feries
Source: <https://www.data.gouv.fr/en/datasets/jours-feries-en-france/>

```{r}
feries <- read.csv("data/jours_feries_metropole.csv")

dat.France$ferie <- is.element(dat.France$jour, feries$date)
```


# Compute ratios

```{r}
computeRatios <- function(dat){
  # dat: dataset
  
  subdat <- dat
  
  # Check that we have data for consecutive dates
  stopifnot(all(diff(as.Date(subdat$jour)) == 1))
  # When it's OK we can just go on
  
  # Index of the final line
  nend <- nrow(subdat)
  
  subdat$ratios7 <- NA # Initialize column
  
  # Ratios
  subdat[8:nend, "ratios7"] <- subdat[8:nend, "P"] / subdat[1:(nend - 7), "P"]
  # Logs (not needed because we will plot on a log scale)
  subdat$logratios7 <- log(subdat$ratios7)
  
  # Sliding average
  subdat$ratios7.slidingave <- sliding.window(subdat$ratios7)
  
  # Number of tests
  subdat[8:nend, "Tratios7"] <- subdat[8:nend, "T"] / subdat[1:(nend - 7), "T"]
  # Sliding average
  subdat$Tratios7.slidingave <- sliding.window(subdat$Tratios7)
  
  subdat # Return result
}

```

```{r figOliverJohnson, fig.height = 6, fig.width = 10.66}
# Doubling time: ln(2) / growthrate, 
# where growth rate is ln(Nt - N0) / t
t2 <- log(2)/2
t4 <- log(2)/4
t1 <- log(2)/1
t05 <- log(2)/(5/7)
t10 <- log(2)/(10/7)

agecl <- 0
dateMin <- "2021-06-15" # min(dat.France$jour)
dateMax <- max(dat.France$jour)


plotRatio <- function(agecl, dateMin, dateMax, miMonth = TRUE, year = FALSE){
  # Subset of the data for this age class and date range
  subdat <- dat.France[which(dat.France$jour >= dateMin & dat.France$jour <= dateMax & dat.France$cl_age90 == agecl), ]
  
  # Remove jours feries to avoid issues
  # (TODO: correction script)
  subdat[subdat$ferie, c("P", "T")] <- NA
  
  head(subdat)
  
  subdat <- computeRatios(subdat)
  
  # Get max value
  xr <- max(abs(subdat$logratios7), na.rm = TRUE)
  
#  plot(as.Date(subdat$jour), subdat$logratios7, col = colJ[as.character(subdat$weekday)], pch = 16, ylim = 1.1*c(-xr, xr))
  
  colCroiss <- "#FF0000"
  colDecroiss <- "#00A5A5"
  
  xrr <- max(abs(subdat$ratios7), na.rm = TRUE) # Not used
  
  par(mgp = c(2.5, 0.5, 0.5), las = 1, 
      mar = c(3, 10, 2, 10), 
      cex = 1)
  ylm <- c(0.5, 1.1*exp(xr)) # ylim

  # Initialize figure
  plot(as.Date(subdat$jour), subdat$ratios7, ylim = ylm, log = "y", axes = FALSE, 
       xlab = "", ylab = "cas(j)/cas(j-7), échelle log", 
       type = "n")
  
  limPlot <- par("usr") # limits of the plot in user coordinates
  op <- 0.25 # Opacity parameter
  
  # Add Shading
  # Decroissance
  polygon(x = as.Date(c(limPlot[1], limPlot[2], limPlot[2], limPlot[1], limPlot[1]), origin = "1970-01-01"), 
          y = c(1, 1, ylm[1], ylm[1], 1), border = NA, col = makeTransparent(colDecroiss, op))
  # Croissance
  polygon(x = as.Date(c(limPlot[1], limPlot[2], limPlot[2], limPlot[1], limPlot[1]), origin = "1970-01-01"), 
          y = c(1, 1, ylm[2], ylm[2], 1), border = NA, col = makeTransparent(colCroiss, op))
  
  # Add horizontal lines for doubling times
  abline(h = 1, lwd = 2)
  colline <- "white" # Line color
  lwdd <- 1.5 # Line width
  
  abline(h = exp(t2), col = colline, lwd = lwdd)
  abline(h = exp(t4), col = colline, lwd = lwdd)
  abline(h = exp(t1), col = colline, lwd = lwdd)
  abline(h = exp(t05), col = colline, lwd = lwdd)
  abline(h = exp(t10), col = colline, lwd = lwdd)
  
  abline(h = exp(-t2), col = colline, lwd = lwdd)
  abline(h = exp(-t4), col = colline, lwd = lwdd)
  abline(h = exp(-t1), col = colline, lwd = lwdd)
  abline(h = exp(-t10), col = colline, lwd = lwdd)
  
  # Add mention direction in shaded areas
  cexlabshade <- 1.2
  text(as.Date((limPlot[1]+limPlot[2])/2, origin = "1970-01-01"), ylm[1], adj = c(0.5, -1), labels = "   Le nombre de cas décroît", col = colDecroiss, font = 1, cex = cexlabshade)
  text(as.Date((limPlot[1]+limPlot[2])/2, origin = "1970-01-01"), ylm[2], adj = c(0.5, 2), labels = "   Le nombre de cas croît", col = colCroiss, font = 1, cex = cexlabshade)
  
  # Add axes
  tckk <- -0.02
  cexx <- 0.9
  days <- seq(as.Date(dateMin), as.Date(dateMax)+30, by = "day")
  
  if(year){
    dateFormat <- "%d/%m/%y"  
  }else{
    dateFormat <- "%d/%m"
  }

  
  axis(1, at = as.Date(range(days)), labels = rep("", 2), tck = 0, pos = ylm[1])
  
  axis(1, at = seq(as.Date(dateMin), as.Date(dateMax)+14, by = "month"), labels = format(seq(as.Date(dateMin), as.Date(dateMax)+14, by = "month"), format = dateFormat), las = 1, cex.axis = cexx, tck = tckk, lwd = 0, lwd.ticks = 1, pos = ylm[1])
  
  if(miMonth){
      axis(1, at = seq(as.Date(dateMin)+16, as.Date(dateMax)+14, by = "month"), labels = format(seq(as.Date(dateMin)+16, as.Date(dateMax)+14, by = "month"), format = dateFormat), las = 1, cex.axis = cexx, tck = tckk, lwd = 0, lwd.ticks = 1, pos = ylm[1])
  }

  
  axis(1, at = days, labels = rep("", length(days)), las = 3, cex.axis = cexx, tck = tckk/2, lwd = 0, lwd.ticks = 1, pos = ylm[1])
  
  axis(2, at = c(seq(0.5, 1, by = 0.1), seq(1.2, 3, by = 0.2)), tck = -.01, pos = as.Date(limPlot[1], origin = "1970-01-01"))
  
  # Add side legend
  par(xpd = TRUE)
  cexleg <- 1
  dj <- 2
  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(t4), labels = "x2 toutes les 4 semaines", adj = c(0, 0.5), cex = cexleg)
  
  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(t2), labels = "x2 toutes les 2 semaines", adj = c(0, 0.5), cex = cexleg)
  
  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(t1), labels = "x2 toutes les semaines", adj = c(0, 0.5), cex = cexleg)
  
  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(t10), labels = "x2 tous les 10 jours", adj = c(0, 0.5), cex = cexleg)

  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(t05), labels = "x2 tous les 5 jours", adj = c(0, 0.5), cex = cexleg)
  
  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(-t4), labels = "÷2 toutes les 4 semaines", adj = c(0, 0.5), cex = cexleg)
  
  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(-t2), labels = "÷2 toutes les 2 semaines", adj = c(0, 0.5), cex = cexleg)
  
  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(-t10), labels = "÷2 tous les 10 jours", adj = c(0, 0.5), cex = cexleg)

  text(x = as.Date(limPlot[2], origin = "1970-01-01") + dj, y = exp(-t1), labels = "÷2 toutes les semaines", adj = c(0, 0.5), cex = cexleg)
  
  par(xpd = FALSE)
  
  points(as.Date(subdat$jour), subdat$ratios7, col = gray(0.3), pch = 16)

  # Just last point, bigger
  nn <- nrow(subdat)
  points(as.Date(subdat[nn, ]$jour), subdat[nn, ]$ratios7, col = gray(0.3), pch = 16, cex = 1.5)
  
  lines(as.Date(subdat$jour), subdat$ratios7.slidingave)
  
  # Add tests
#  points(as.Date(subdat$jour), subdat$Tratios7, col = gray(0.8), pch = 16)
  
  
  mtext("Inspiré des figures de @BristOliver 
Données: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/# (en date de prélèvement)
Code: https://github.com/flodebarre/covid_indicateurs/blob/main/tauxCroissance.Rmd", side = 1, line = 2., adj = 0, cex = 0.5, family = "mono")
  
  mtext(paste0("Ratio du nombre de cas détectés en France d'une semaine à l'autre
(en date de prélèvement), jusqu'au ", format(as.Date(dateMax), format = dateFormat)), font = 1, cex = 1.2, line = -0.75)
  
}


plotRatio(agecl, "2021-06-01", dateMax)
```


```{r figOliverJohnsonLong, fig.height = 6, fig.width = 12.5}
plotRatio(agecl, "2020-05-01", dateMax, miMonth = FALSE, year = TRUE)
```

# Tests

```{r, fig.height = 6, fig.width = 10.66}
par(mar = c(3, 8, 2, 8), las = 1)

agecl <- 0
dateMin <- "2021-05-11"
dateMax <- "2021-07-10"

computeWeekdays <- function(agecl, dateMin, dateMax){
    # Subset of the data for this age class and date range
  subdat <- dat.France[which(dat.France$jour >= dateMin & dat.France$jour <= dateMax & dat.France$cl_age90 == agecl), ]

  # Initialize new column for non holidays
  subdat$keep <- TRUE

  # Annotate days around a holiday (-3, +3)  
for(i in which(subdat$ferie)){
  subdat[seq(max(i-3, 1), min(i+3, nrow(subdat)), by = 1), "keep"] <- FALSE
}
  # Remove days around a holiday to avoid skewing data
  sub2 <- subdat[which(subdat$keep), ]
  
  # Compute tests by weekday
  byday <- aggregate(sub2$T, by = list(weekday = sub2$weekday), FUN = sum)  
  # Compute frequencies
  byday$p <- byday$x / sum(byday$x)
  # Return table
  byday
}


P.yearBefore <- computeWeekdays(0, "2021-01-01", "2021-05-01")
P.beforePass <- computeWeekdays(0, "2021-05-10", "2021-07-10")
P.afterPassBeforeDeremb <- computeWeekdays(0, "2021-08-09", "2021-10-10")
P.afterPassAfterDeremb <- computeWeekdays(0, "2021-10-16", "2021-11-19")

P.yearBefore$type <- 0
P.beforePass$type <- 1    
P.afterPassBeforeDeremb$type <- 2
P.afterPassAfterDeremb$type <- 3

P <- rbind(P.yearBefore, P.beforePass, P.afterPassBeforeDeremb, P.afterPassAfterDeremb)
P


P$weekday

barplot(p ~ weekday + type, data = P, beside = TRUE, xlab = "type", ylab = "Proportion des tests")

barplot(p ~ type + weekday, data = P, beside = TRUE, xlab = "jour de la semaine", ylab = "Proportion des tests")

plot(P$weekday, P$p, ylim = c(0, max(P$p)), yaxs = "i", frame.plot = FALSE, col = P$type, xlab = "jour de la semaine", ylab = "Proportion des tests")

  subdat <- dat.France[which(dat.France$jour >= dateMin & dat.France$jour <= dateMax & dat.France$cl_age90 == agecl), ]

plot(as.Date(subdat$jour), subdat$T, col = colJ[as.character(subdat$weekday)], pch = 16, 
     ylim = c(0, 1.15*max(subdat$T)), 
     xaxs = "i", yaxs = "i", frame.plot = FALSE, 
     xlab = "", ylab = "")


par(xpd = FALSE)
deremb <- as.Date("2021-10-15")
abline(v = deremb)
par(xpd = TRUE)
text(x = deremb, y = max(subdat$T), labels = " fin du remboursement pour les non-vaccinés
 sans prescription médicale", adj = c(0, 0.5), cex = 0.7)

par(xpd = FALSE)

legend("top", horiz = TRUE, col = colJ, legend = c("Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"), pch = 16, box.lwd = 0)

title("Nombre de tests effectués")

```

# Positive cases

```{r figCasPos, fig.height = 6, fig.width = 10.66}
par(mar = c(4, 3, 3, 1))
agecl <- 0
dateMin <- "2021-06-01" # min(dat.France$jour)
dateMax <- max(dat.France$jour)


plotFigP <- function(agecl, dateMin, dateMax){

  # Subset of the data for this age class and date range
  subdat <- dat.France[which(dat.France$jour >= dateMin & dat.France$jour <= dateMax & dat.France$cl_age90 == agecl), ]
  
  # Remove jours feries to avoid issues
  # (TODO: correction script)
  subdat[subdat$ferie, c("P", "T")] <- NA

  # Compute ratios  
  subdat <- computeRatios(subdat)

  # Look for abs max ratio value
  xrr <- max(abs(subdat[!subdat$ferie, "logratios7"]), na.rm = TRUE) # Not used
  maxVal <- ceiling(xrr*10)/10

  # Define color scale
  # Obtained by merging two color scales
  nn <- 100 # Number of values
  x1 <- sequential_hcl(nn/2, "Inferno")
  x2 <- sequential_hcl(nn/2, "BluYl")
  xx <- rev(c(x1, rev(x2)))
  #plot(seq_along(xx), col = xx, pch = 16)

  colScale <- data.frame(col = xx, logval = seq(-maxVal, maxVal, length.out = length(xx)))
  colScale
  colScale$val <- exp(colScale$logval)
  colScale$logval <- seq(log)
  #plot(colScale$val, rep(1, nrow(colScale)), col = xx, pch = 16)
  
  # get color corresponding to a particular value
  getIndex <- function(value){
    which(value < colScale$val)[1] - 1
  }
  getCol <- function(value){
    i <- getIndex(value)
    colScale[i, "col"]
  }
  
  getCols <- function(values){
    vapply(values, getCol, FUN.VALUE = "X")
  }

  getPCH <- function(wkday){
    switch(wkday, 
           "1" = 21, 
           "2" = 22, 
           "3" = 23, 
           "4" = 21, 
           "5" = 22, 
           "6" = 24, 
           "7" = 25)
  }
  getPCHs <- function(weekdays){
    vapply(weekdays, getPCH, FUN.VALUE = 1)
  }
  
  getCex <- function(wkday){
    cex1 <- 1.75
    cex2 <- 0.8*cex1
    switch(wkday, 
           "1" = cex1, 
           "2" = cex1, 
           "3" = cex1, 
           "4" = cex2, 
           "5" = cex2, 
           "6" = cex2, 
           "7" = cex2)
  }
  getCexs <- function(weekdays){
    vapply(weekdays, getCex, FUN.VALUE = 1)
  }


layout(matrix(c(1, 1, 2, 3), ncol = 2), widths = c(10, 3), heights = c(5, 5))

fgg <- gray(1)
par(bg = gray(0.65), 
    fg = gray(1), 
    col.axis = fgg, col.lab = fgg)
par(las = 1)
par(mar = c(5, 4, 4, 1))

par(mgp = c(2., 0.5, 0))

plot(as.Date(subdat$jour), subdat$P, bg = getCols(subdat$ratios7), pch = getPCHs(subdat$weekday), cex = getCexs(subdat$weekday), col = NA, 
       yaxs = "i", xaxs = "i",  
       ylim = c(0, 1.1*max(subdat$P, na.rm = TRUE)), 
       frame.plot = FALSE, 
     axes = FALSE, 
     xlab = "", 
     ylab = "")
  
  limPlot <- par("usr") # limits of the plot in user coordinates
  op <- 0.25 # Opacity parameter
  
  # Add Shading
  par(xpd = TRUE)

  dj <- 7
  polygon(x = as.Date(c(limPlot[1], limPlot[2]+dj, limPlot[2]+dj, limPlot[1], limPlot[1]), origin = "1970-01-01"), y = c(0, 0, limPlot[4], limPlot[4], 0), border = NA)
  
  dy <- 5000
  for(i in seq(0, max(subdat$P, na.rm = TRUE), by = dy)){
    lines(c(limPlot[1], limPlot[2]+dj), rep(i, 2), col = gray(1, 0.5))
  }

    # Add axes
axis(2, pos = limPlot[1], col = "white", lwd = 0, 
     at = seq(0, max(subdat$P, na.rm = TRUE), by = 5000))


xx <- seq(as.Date("2020-05-01"), as.Date(dateMax), by = "month")

axis.Date(1, at = xx, labels = format(xx, "%b\n%Y"), lwd = 0, lwd.ticks = 1, hadj = 0.5, padj = 0.5)

  # Plot points  
  points(as.Date(subdat$jour), subdat$P, bg = getCols(subdat$ratios7), pch = getPCHs(subdat$weekday), cex = getCexs(subdat$weekday), col = NA)
  par(xpd = FALSE)


# Title
mtext("Nombre de cas positifs par jour de test,
coloriés selon le ratio par rapport à la semaine précédente", side = 3, line = 0.5)
mtext(paste0("France entière, tous âges
Données brutes, sans les jours fériés (jusqu'au ", format(as.Date(dateMax), "%d/%m"), ")" ), side = 3, line = -1.75, cex = 0.8)

  mtext("@flodebarre, ratio inspiré des figures de @BristOliver 
Données: https://www.data.gouv.fr/fr/datasets/donnees-relatives-aux-resultats-des-tests-virologiques-covid-19/# (en date de prélèvement)
Code: https://github.com/flodebarre/covid_indicateurs/blob/main/tauxCroissance.Rmd", side = 1, line = 3.5, adj = 0, cex = 0.5, family = "mono")
  
#-----------------------------
xlm <- c(-0.5, 1)
  
par(mar = c(2, 2, 4, 2))
plot(rep(0, nn), seq_len(nn), col = colScale$col, pch = 15, axes = FALSE, xlab = "", ylab = "", 
      xlim = xlm, 
     cex = 2)
mtext("Ratio du nb de cas 
d'une semaine à l'autre
(échelle log)", cex = 0.8)

vals <- c(0.3, 0.5, 0.75, 1, 1.5, 2, 3)
yy <- vapply(vals, getIndex, FUN.VALUE = 1)
xxx <- 0.2
text(x = rep(-xxx, length(yy)), yy, labels = vals, adj = 1)

vals2 <- exp(c(-t1, -t2, 0, t2, t1, t05))
yy2 <- vapply(vals2, getIndex, FUN.VALUE = 1)

par(xpd = TRUE)
#points(rep(xxx, length(yy2)), yy2)
text(x = rep(xxx, length(yy2)), yy2, 
     labels = c("÷2 ttes les 2 semaines", 
                "÷2 ttes les semaines", 
                "constant", 
                "x2 ttes les 2 semaines", 
                "x2 ttes les semaines", 
                "x2 ts les 5 jours"), adj = 0, cex = 0.75)
par(xpd = FALSE)


#-------------------------------
dxx <- 1
plot(rep(0, 7), rev(1:7), pch = getPCHs(1:7), bg = "white", fg = NA, xlim = xlm, 
     ylim = c(1 - dxx, 7 + dxx), 
     cex = getCexs(1:7), 
     axes = FALSE, frame.plot = FALSE, 
     xlab = "", ylab = "")
text(rep(0.2, 7), rev(1:7), labels = c("Lundi", "Mardi", "Mercredi", "Jeudi", "Vendredi", "Samedi", "Dimanche"), adj = c(0, 0.5))
mtext("
      
Jour de la semaine", cex = 0.8)

}

plotFigP(agecl, dateMin, dateMax)
```


```{r figCasPosAll, fig.height = 6, fig.width = 15}
plotFigP(agecl, "2020-05-01", dateMax)

```


```{r, eval = FALSE}
#---------
  
  plot(subdat$weeknb, subdat$P, bg = getCols(subdat$ratios7), pch = getPCHs(subdat$weekday), cex = getCexs(subdat$weekday), col = NA)
# Remove jours feries


  plot(subdat[!subdat$ferie, "ratios7"])

head(subdat)  

plot(subdat$weeknb, subdat$P)    
```

# Essais

```{r, include = FALSE, eval = FALSE}


display.brewer.pal(n = 8, name = 'Dark2')

xx <- sequential_hcl(101, "Red-Blue")

plot(seq_along(xx), col = xx, pch = 15)

display.brewer.pal(n = 101, name = 'RdBu')


nn <- 20
plot.new()
lgd_ = rep(NA, nn)
lgd_[c(1,6,nn)] = c(1,6,nn)
legend(x = 0.5, y = 0.5,
       legend = lgd_,
       fill = colorRampPalette(colors = c('black','red3','grey96'))(nn),
       border = NA,
       y.intersp = 0.5,
       cex = 2, text.font = 2)


colfunc <- colorRampPalette(c("red", "blue"))
layout(matrix(1:2,ncol=2), width = c(2,1),height = c(1,1))
plot(1:20, 1:20, pch = 19, cex=2, col = colfunc(20))

legend_image <- as.raster(matrix(colfunc(20), ncol=1))
plot(c(0,2),c(0,1),type = 'n', axes = F,xlab = '', ylab = '', main = 'legend title')
text(x=1.5, y = seq(0,1,l=5), labels = seq(0,1,l=5))
rasterImage(legend_image, 0, 0, 1,1)



```

